# Ansible Playbook for Dynamic Network Graph and Validation
- hosts: all
  gather_facts: yes
  gather_subset:
    - network
  vars:
    testing_with_fake_peer: true
    FAKE_ENDPOINT: "192.192.192.192:51820"
    FAKE_ALLOWED_IPS: "192.192.192.0/24"
  tasks:
    - name: Collect network information
      include_tasks: collect_network_info.yaml

    - name: Save collected data to a JSON file
      copy:
        content: "{{ hostvars | to_json }}"
        dest: /tmp/hostvars.json
      run_once: true
      delegate_to: localhost
      when: true 
      tags: debug

    - name: Render graph in DOT format
      template:
        src: templates/graph.dot.j2
        dest: /tmp/graph.dot
      run_once: true
      delegate_to: localhost

    - name: Convert DOT file to PNG
      shell: dot -Tpng /tmp/graph.dot -o ./graph.png
      args:
        executable: /bin/bash
      register: dot_to_png_result
      run_once: true
      delegate_to: localhost
