---
# Paths
modulefiles_base_path: "/usr/share/modulefiles"

# Packages
cpp_compiler_pkg: "gcc-c++"
environment_modules_pkg: "environment-modules"

# MPI Implementations
mpi_implementations:
  - module: mpi/openmpi-x86_64
    mpi_packages: "openmpi openmpi-devel"
    env_vars: |
      setenv OMPI_MCA_pml ob1
      setenv OMPI_MCA_btl tcp,self
  - module: mpi/mpich-x86_64
    mpi_packages: "mpich mpich-devel"
    env_vars: ""
