environment_modules_pkg: "environment-modules"
libnuma_path: "/usr/lib64/libnuma.so.1"
libnuma_dest: "/usr/lib64/libnuma.so"
qemu_pkgs: ["qemu-kvm", "qemu-img", "libvirt", "virt-install", "virt-manager", "libvirt-nss"]
report_tools: ["enscript", "ImageMagick", "python3-img2pdf", "poppler-utils", "rsync", "ghostscript"]
