environment_modules_pkg: "environment-modules"
libnuma_path: "/usr/lib/x86_64-linux-gnu/libnuma.so.1"
libnuma_dest: "/usr/lib/x86_64-linux-gnu/libnuma.so"
qemu_pkgs: ["qemu-system-x86", "qemu-utils", "libvirt-daemon-system", "virtinst", "virt-manager", "libnss-libvirt"]
report_tools: ["enscript", "imagemagick", "img2pdf", "poppler-utils", "rsync", "ghostscript"]
