---
dev_tools_package: "@Development Tools"
dns_utils_package: "bind-utils"
pdsh_ssh_package: "pdsh-rcmd-ssh"

mpi_implementations:
  - module: mpi/openmpi-x86_64
    mpi_packages: "openmpi openmpi-devel"
    env_vars: |
      setenv OMPI_MCA_pml ob1
      setenv OMPI_MCA_btl tcp,self
  - module: mpi/mpich-x86_64
    mpi_packages: "mpich mpich-devel"
    env_vars: ""
