- name: Set IOR Config options 
  set_fact:
    ior_config_option: '' # no config options for beegfs install 

- include_tasks: tasks/beegfs/install_beegfs.yaml

- include_tasks: tasks/shared/install_tools.yaml

- include_tasks: tasks/shared/disable_firewall_selinux.yaml

- include_tasks: tasks/shared/sanity_test.yaml
  vars: { sanity_debug_msg: "At the end of beegfs install" }
