flowchart TD
  subgraph Inputs["<b><u>User Inputs</u><b>"]
    direction LR
    SystemDescription@{ shape: doc, label: "System Description" }
    %%SystemDescription["System Description"]
    SoftwareInstallation@{ shape: doc, label: "Software Installation Playbook"}
    ClusterConfiguration@{ shape: doc, label: "Cluster Configuration Playbook"}

    subgraph Options["<i><u>Optional</u></i>"]
      direction LR
      TestScript@{ shape: doc, label:" Test Playbook"}
      Patch@{ shape: doc, label:" Software Patch"}
    end

    SystemDescription ~~~ SoftwareInstallation ~~~ ClusterConfiguration ~~~ Patch ~~~ TestScript
  end

  %% PHASES DEFINED HERE
  AnsiblePrepare(("<br><b>PHASE 0</b><br>Ansible<br>Prepare<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;"))
  AnsibleGold(("<br><b>PHASE 1</b><br>Ansible<br>Create Gold VMs<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;"))
  AnsibleNetwork(("<br><b>PHASE 2</b><br>Ansible<br>Create Networking<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;"))
  AnsibleConfigure(("<b>PHASE 4</b><br>Ansible<br>Configure<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;"))
  AnsibleTest(("<b>PHASE 5</b><br>Ansible<br>Test<br>--<i>optional</i>--<br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;"))
  style AnsiblePrepare fill:#ADD8E6,stroke:#333,stroke-width:1px
  style TofuCreateVMs fill:#ADD8E6,stroke:#333,stroke-width:1px
  style AnsibleConfigure fill:#ADD8E6,stroke:#333,stroke-width:1px
  style AnsibleGold fill:#ADD8E6,stroke:#333,stroke-width:1px
  style AnsibleNetwork fill:#ADD8E6,stroke:#333,stroke-width:1px
  style AnsibleTest fill:#ADD8E6,stroke:#333,stroke-width:1px
  
  %%SystemDescription --> AnsiblePrepare
  Inputs --> AnsiblePrepare

  subgraph Outputs[" "]
    direction LR
    Makefile@{shape: card, label: "<u>Makefile</u>\nmake all\n-- clean\n-- status\n-- phase[1-5]\n-- phase[1-5]-clean"}
    GoldVMInventory@{ shape: doc, label: "Gold VM Inventory"}
    NetworkInventory@{ shape: doc, label: "Network Inventory"}
    ClusterDesc@{ shape: doc, label:"Cluster Description"}
    Makefile ~~~ GoldVMInventory ~~~ NetworkInventory ~~~ ClusterDesc
  end

  AnsiblePrepare --> Outputs

  %% AnsibleGold ~~~ AnsibleNetwork

  %% GoldVMInventory --> AnsibleGold
  %% NetworkInventory --> AnsibleNetwork

  Outputs --> AnsibleGold
  Outputs --> AnsibleNetwork

  VirtualCluster@{ shape: processes, label: "<br>Empty<br>Virtual<br>Cluster<br><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;"}

  AnsibleGold --> StashedGoldVMs
  AnsibleNetwork --> VirtualCluster

  %%TofuCreateVMs{{"OpenTofu<br>Create VMs"}}
  TofuCreateVMs(("<br><b>PHASE 3</b><br>OpenTofu<br>Create VMs<br><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;"))
  Outputs --> TofuCreateVMs
  VirtualCluster --> TofuCreateVMs
  Inputs --> TofuCreateVMs
  Inputs --> AnsibleGold

  VMCluster@{ shape: processes, label: "<br>Unconfigured<br>VM<br>Cluster<br><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;"}

  StashedGoldVMs --> TofuCreateVMs
  TofuCreateVMs --> VMCluster
  

  Inputs --> AnsibleConfigure
  VMCluster --> AnsibleConfigure --> ConfiguredCluster

  ConfiguredCluster@{ shape: processes, label: "<br>Configured<br>VM<br>Cluster<br><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;"}

  TestResults@{ shape: doc, label: "TestResults"}
  ConfiguredCluster --> AnsibleTest --> TestResults
  Inputs --> AnsibleTest

  %% Files
  style NetworkInventory fill:#D3D3D3,stroke:#333,stroke-width:1px
  style GoldVMInventory fill:#D3D3D3,stroke:#333,stroke-width:1px
  style ClusterDesc fill:#D3D3D3,stroke:#333,stroke-width:1px
  style SystemDescription fill:#D3D3D3,stroke:#333,stroke-width:1px
  style SoftwareInstallation fill:#D3D3D3,stroke:#333,stroke-width:1px
  style ClusterConfiguration fill:#D3D3D3,stroke:#333,stroke-width:1px
  style TestScript fill:#D3D3D3,stroke:#333,stroke-width:1px,stroke-dasharray: 5 5

  style VMCluster fill:#EEAAFF,stroke:#333,stroke-width:2px
  style ConfiguredCluster fill:#CCFFFF,stroke:#333,stroke-width:2px
  style VirtualCluster fill:#CCEECC,stroke:#333,stroke-width:2px


