# Define your targeted changes
io500_config_updates:
  - section: global
    option: timestamp-resultdir
    value: "FALSE"
  - section: mdtest-hard-delete
    option: run
    value: "TRUE"
  - section: mdtest-easy-delete
    option: run
    value: "TRUE"
  - section: ior-easy
    option: run
    value: "TRUE"
  - section: ior-easy-write
    option: run
    value: "TRUE"
  - section: mdworkbench
    option: run
    value: "FALSE"
  - section: mdworkbench-create
    option: run
    value: "FALSE"
  - section: find-easy
    option: run
    value: "TRUE"
  - section: ior-hard
    option: run
    value: "FALSE"
  - section: ior-hard-write
    option: run
    value: "FALSE"
  - section: find
    option: run
    value: "TRUE"
  - section: ior-rnd4K-easy-read
    option: run
    value: "TRUE"
  - section: find-hard
    option: run
    value: "TRUE"
  - section: mdworkbench-bench
    option: run
    value: "FALSE"
  - section: ior-easy-read
    option: run
    value: "TRUE"
  - section: ior-hard-read
    option: run
    value: "FALSE"
  - section: mdworkbench-delete
    option: run
    value: "FALSE"
