---
# Paths
modulefiles_base_path: "/usr/share/modules/modulefiles"

# Packages
cpp_compiler_pkg: "g++"
environment_modules_pkg: "environment-modules"

# MPI Implementations
mpi_implementations:
  - module: mpi/openmpi-x86_64
    mpi_packages: "openmpi-bin libopenmpi-dev"
    mpirun_args: "--prefix $MPI_HOME --mca plm_rsh_args '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"
    env_vars:
      - name: OMPI_MCA_pml
        value: ob1
      - name: OMPI_MCA_btl
        value: tcp,self
  # mpich doesn't work on Ubuntu for some reason
  #- module: mpi/mpich-x86_64
  #  mpirun_args: ""
  #  mpi_packages: "mpich libmpich-dev"
  #  env_vars: []

# MPI builds supplied by Xem for Ubuntu 24 hosts.
existing_mpi_implementations:
  - path: /share/u24-ofi/mpich
    env_vars:
      - name: FI_PROVIDER
        value: verbs
  - path: /share/u24-ofi/ompi
  - path: /share/u24-ucx/mpich
    env_vars:
      - name: UCX_LOG_LEVEL
        value: error
      - name: FI_PROVIDER
        value: verbs
  - path: /share/u24-ucx/ompi
    env_vars:
      - name: UCX_LOG_LEVEL
        value: error
