# User & SSH
lab_user: "root"
  
pnfs_local_src: /opt/pnfscore/

# Whether to run rondb data on same node as rondb mgr
rondb_colocate_mgr: true

# Remote Base Paths
lab_remote_base: "/opt/pnfs-ng"
lab_rondb_base: "/opt/rondb"
lab_mds_conf_dir: "/etc/pnfs-mds"
lab_mds_run_dir: "/var/lib/pnfs-mds"

# Source & Build Paths (Local to the controller/MDS0)
lab_source_dir: "{{ lab_remote_base }}"
lab_build_dir: "{{ lab_source_dir }}/rondb-build"

# RonDB Specifics
lab_rondb_version: "24.10.0"
lab_rondb_data_dir: "/var/lib/rondb-data"
lab_rondb_schema: "pnfs_mds"

# Network
lab_mds_nfs_port: 2049
lab_mds_grpc_port: 50051
lab_ds_export_path: "/export/ds"

lab_client_mount: "/mnt/pnfs"

rondb_bin: "{{ lab_rondb_base }}/bin"
rondb_data: "{{ lab_rondb_data_dir }}/data"
