- name: Check if rsync is installed
  command: "command -v rsync"
  register: rsync_check
  ignore_errors: yes

- block:
    - name: Warn if rsync is not installed
      debug:
        msg: "WARNING. SANITY FAILURE: rsync is very strangely not installed. Attempting to reinstall it"

    - name: Install rsync if not installed
      ansible.builtin.package:
        name: rsync
        state: present

    - name: Confirm rsync installation
      command: which rsync
      register: rsync_confirm

    - name: Validate rsync installation
      fail:
        msg: "Failed to install rsync. Please install it manually."
      when: rsync_confirm.rc != 0

    - name: Print success message
      debug:
        msg: "Sanity Restored: rsync is installed and available at {{ rsync_confirm.stdout }}."
      when: rsync_confirm.rc == 0 
  when: rsync_check.rc != 0 
