- name: Check connectivity
  ping:

- name: Notify if VM is a client
  debug:
    msg: "{{ inventory_hostname }} is a client"
  when: "'clients' in group_names"

- name: Notify if VM is a server
  debug:
    msg: "{{ inventory_hostname }} is a server"
  when: "'servers' in group_names"

