---
- name: Discover mpi_bin path using shared module loader
  ansible.builtin.include_tasks: run_with_mpi_module.yaml
  vars:
    mpi_module: "{{ mpi.module }}"
    commands: |
      REAL_MPIRUN=$(type -p mpirun)
      
      if [ -z "$REAL_MPIRUN" ]; then
        echo "CRITICAL_ERROR: mpirun could not be found in PATH" >&2
        exit 1
      else
        dirname "$REAL_MPIRUN"
      fi

# This acts as our "return" payload mechanism
- name: Set return facts for the host
  ansible.builtin.set_fact:
    # Notice we updated the variable name to match the shared task's register definition
    mpi_bin: "{{ mpi_shell_result.stdout_lines[-1] | trim }}"

- name: Set the MPI label base
  ansible.builtin.set_fact:
    mpi_label: "{{ mpi.module | basename | regex_replace('-x86_64', '') }}"
