---
- name: Set OSU build variables for {{ mpi_implementation.module }}
  set_fact:
    osu_version: "7.5.2"
    osu_prefix: "/usr/local/osu/{{ mpi_implementation.module | regex_replace('/', '_') }}"
    osu_src_dir: "/tmp/osu-micro-benchmarks/{{ mpi_implementation.module | regex_replace('/', '_') }}"
    osu_tarball: "osu-micro-benchmarks-7.5.2.tar.gz"
    osu_url: "https://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-7.5.2.tar.gz"

- name: Set OSU flag used to avoid repeating work 
  set_fact:
    osu_stamp: "{{ osu_prefix }}/.installed"

- name: Check if OSU already installed
  stat:
    path: "{{ osu_stamp }}"
  register: osu_installed

- block:
    - name: Install required build packages
      ansible.builtin.package:
        name:
          - "{{ environment_modules_pkg }}"
          - autoconf
          - automake
          - libtool
          - make
          - gcc
          - "{{ cpp_compiler_pkg }}"
        state: present

    - name: Ensure build directory is clean
      ansible.builtin.file:
        path: "{{ osu_src_dir }}"
        state: absent

    - name: Create unique build directory
      ansible.builtin.file:
        path: "{{ osu_src_dir }}"
        state: directory
        mode: '0755'

    - name: Download OSU tarball using curl
      ansible.builtin.command:
        cmd: "curl -L {{ osu_url }} -o /tmp/{{ osu_tarball }}"
        creates: "/tmp/{{ osu_tarball }}"
      # This ensures curl uses the system proxy settings without hard-coding them
      environment:
        http_proxy: "{{ ansible_env.http_proxy | default('') }}"
        https_proxy: "{{ ansible_env.https_proxy | default('') }}"

    - name: Extract OSU
      ansible.builtin.unarchive:
        src: "/tmp/{{ osu_tarball }}"
        dest: "{{ osu_src_dir }}"
        remote_src: true
        extra_opts: ["--strip-components=1"]

    - name: Debug mpi module
      debug:
        var: mpi_implementation

    - name: Configure, Build, and Install OSU with {{ mpi_implementation.module }}
      ansible.builtin.include_tasks: ../tasks/run_with_mpi_module.yaml
      vars:
        mpi_module: "{{ mpi_implementation.module }}"
        working_dir: "{{ osu_src_dir }}"
        commands: |
          MPI_LIB_PATH=$(readlink -f $(dirname "$MPICC_PATH")/../lib)
          ./configure CC="$MPICC_PATH" CXX="$MPICXX_PATH" \
              LDFLAGS="-Wl,-rpath,${MPI_LIB_PATH}" \
              --prefix="{{ osu_prefix }}"
          make -j$(nproc)
          make install

    - name: Create installation stamp
      ansible.builtin.file:
        path: "{{ osu_prefix }}"
        state: directory
        mode: '0755'
      
    - name: Touch stamp file
      ansible.builtin.file:
        path: "{{ osu_stamp }}"
        state: touch

  when: not osu_installed.stat.exists
