---
- name: Set modulefile path for {{ module_name }}
  ansible.builtin.set_fact:
    target_modulefile: "{{ modulefiles_base_path }}/{{ module_name }}"

- name: Ensure modulefile directory exists
  ansible.builtin.file:
    path: "{{ target_modulefile | dirname }}"
    state: directory
    mode: "0755"

- name: Ensure modulefile {{ target_modulefile }} has magic cookie header
  ansible.builtin.lineinfile:
    path: "{{ target_modulefile }}"
    line: "#%Module"
    insertbefore: BOF
    create: true
    mode: "0644"

- name: Write modulefile for {{ module_name }}
  ansible.builtin.blockinfile:
    path: "{{ target_modulefile }}"
    marker: "# {mark} Managed MPI Environment"
    block: |
      prepend-path    PATH            {{ module_bin_path }}
      prepend-path    LD_LIBRARY_PATH {{ module_lib_path }}
      {% if module_tool_bin_path is defined %}
      prepend-path    PATH            {{ module_tool_bin_path }}
      {% endif %}
      {% if module_tool_lib_path is defined %}
      prepend-path    LD_LIBRARY_PATH {{ module_tool_lib_path }}
      {% endif %}
      setenv          MPI_HOME        {{ module_home | default(module_bin_path | dirname) }}
      {% for env_var in module_env_vars | default([]) %}
      setenv          {{ env_var.name }} {{ env_var.value }}
      {% endfor %}
    create: true
    mode: "0644"
