# File: playbooks/tasks/path_to_mpi_specific_src.yaml
---
- name: Determine dynamic source installation directory
  ansible.builtin.set_fact:
    mpi_paths: "{{ mpi_paths | default({}) | combine({ target_executable: '/usr/local/src/' ~ target_executable ~ '_' ~ target_mpi_label }) }}"
