---
# tasks/write_mpi_hostfile.yaml

- name: Actually write {{ hostfile_path }} for {{ mpi_module }} 
  ansible.builtin.copy:
    content: |
      {% for host in hosts -%}
      {{ hostvars[host]['ansible_fqdn'] }}{{ ' slots=1' if 'openmpi' in mpi_module else '' }}
      {% endfor %}
    dest: "{{ hostfile_path }}"
    mode: '0644'
