---
# tasks/write_mpi_hostfile.yaml

- name: Actually write {{ hostfile_path }} for {{ mpi_module }} 
  ansible.builtin.copy:
    content: |
      {% for host in hosts -%}
      {% set host_slots = (slots_by_host | default({})).get(host, 1) | int -%}
      {{ hostvars[host]['ansible_fqdn'] }}{{ ' slots=' ~ host_slots ~ ' max_slots=' ~ host_slots if 'openmpi' in mpi_module else '' }}
      {% endfor %}
    dest: "{{ hostfile_path }}"
    mode: '0644'
