- name: Create Gold VM Images
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VM definitions for gold VMs combining individual values with defaults 
      set_fact:
        vm_definitions: "{{ vms.individual | map('combine', vms.defaults) | list }}"
      tags: makeclean # This is needed to ensure this is done when makeclean is passed 

    - name: Install each VM
      include_tasks: install_vm.yaml
      with_items: "{{ vm_definitions }}"
      loop_control:
        label: "{{ item.name }}"
      tags: makeclean  # This is needed to ensure the tasks are included when makeclean is passed

    - name: Save each VM to qcow format
      include_tasks: vm_to_qcow.yaml
      with_items: "{{ vm_definitions }}"
      loop_control:
        label: "{{ item.name }}"
      tags: makeclean  # This is needed to ensure the tasks are included when makeclean is passed

