---
- name: Install MPI packages for {{ mpi.module }}
  ansible.builtin.package:
    name: "{{ mpi.mpi_packages.split() }}"
    state: present

- name: Set modulefile path
  set_fact:
    target_modulefile: "{{ modulefiles_base_path }}/{{ mpi.module }}"

- name: Ensure modulefile directory exists
  ansible.builtin.file:
    path: "{{ target_modulefile | dirname }}"
    state: directory
    mode: "0755"

- name: Ensure modulefile has magic cookie header
  ansible.builtin.lineinfile:
    path: "{{ target_modulefile }}"
    line: "#%Module"
    insertbefore: BOF
    create: yes
    mode: "0644"

- name: Add env vars to modulefile
  ansible.builtin.blockinfile:
    path: "{{ target_modulefile }}"
    marker: "# {mark} MPI-specific environment variables"
    block: "{{ mpi.env_vars }}"
    create: yes
    mode: "0644"
  when: mpi.env_vars | length > 0
