---
- name: Configure Empty Cluster 
  hosts: all
  gather_facts: yes

  tasks:
    - block:
      - name: Configure ssh
        include_tasks: ../shared/configure_ssh.yaml
      tags: setup

- import_playbook: ../shared/install_osu_micro_benchmarks.yaml
