---
- name: Configure Empty Cluster 
  hosts: all
  gather_facts: yes

  tasks:
    - block:
      - name: Configure ssh
        include_tasks: ../shared/configure_ssh.yaml

      - name: Install OSU benchmarks
        include_tasks: ../shared/install_osu_micro_benchmarks.yaml
        when: false # this is now down during creation of the golds
      
      tags: setup
