- name: Install Necessary Software for the Empty Cluster 
  set_fact:
    ior_config_option: '' # no config options for beegfs install 

- name: Ensure marker directory exists 
  include_tasks: ../shared/ensure_marker_dir.yaml

- include_tasks: ../shared/install_tools.yaml

- include_tasks: ../shared/disable_firewall_selinux.yaml

- include_tasks: ../shared/install_mpi.yaml

- include_tasks: ../shared/install_osu_micro_benchmarks.yaml
