- name: Ensure marker directory exists
  file:
    path: /var/log/ansible/{{ UNIQUE_TAG }}
    state: directory
    mode: '0755'
  register: marker_dir_status

- set_fact:
    marker_dir: "{{ marker_dir_status.path }}"

