- name: Install necessary prerequisites
  hosts: all 
  gather_facts: true
  become: true
  tasks:

  - name: Install IOR and MPI Hello World and IO500
    when: "'clients' in group_names"
    block:
    - name: Load Base OS Family Variables
      include_vars: "tools_{{ ansible_os_family }}.yml"

    - name: Install and build IOR + MPI Hello
      include_tasks: install_ior.yaml
      loop: "{{ mpi_implementations }}"
      loop_control:
        loop_var: mpi
