- name: Install OSU micro_benchmarks with each MPI
  ansible.builtin.include_tasks: tasks/install_osu_micro_benchmarks.yaml
  loop:
    - mpi/openmpi
    - mpi/mvapich2
  loop_control:
    loop_var: mpi_module
