- name: Install MPIs
  block:
    - name: Load OS-specific MPI variables
      include_vars: "../vars/mpi_{{ ansible_os_family }}.yml"

    - name: Install MPI versions 
      include_tasks: "../tasks/install_mpi.yaml"
      loop: "{{ mpi_implementations }}"
      loop_control:
        loop_var: mpi
  become: true
