- name: Gather facts
  setup:

- name: Include set_hostname 
  include_tasks: set_hostname.yaml

- name: Enable EPEL repository
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Ensure Development Tools are installed
  ansible.builtin.dnf: # it's not clear that package will work for group tools so use dnf
    name: "@Development Tools"
    state: present

- name: Install qemu-guest-agent 
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present

- name: Enable qemu-guest-agent service
  systemd:
    name: qemu-guest-agent
    enabled: yes
    state: started

- name: Install pdsh on target machines
  ansible.builtin.package:
    name: pdsh-rcmd-ssh
    state: present

- name: Install pdsh on target machines
  ansible.builtin.package:
    name: pdsh
    state: present

- name: Install rsync on target machines
  ansible.builtin.package:
    name: rsync
    state: present

- name: Install nslookup on target machines
  ansible.builtin.package:
    name: bind-utils
    state: present

- name: Ensure cloud-init is installed
  ansible.builtin.package:
    name: cloud-init
    state: present

- name: Enable and start cloud-init service
  ansible.builtin.systemd:
    name: cloud-init
    enabled: yes
    state: started

- name: Enable cloud-init-local service
  ansible.builtin.systemd:
    name: cloud-init-local
    enabled: yes

- name: Enable cloud-config service
  ansible.builtin.systemd:
    name: cloud-config
    enabled: yes

- name: Enable cloud-final service
  ansible.builtin.systemd:
    name: cloud-final
    enabled: yes

# install_and_build_mpi.yml
- name: Install and build IOR + MPI Hello for each MPI implementation
  include_tasks: install_ior.yaml
  loop:
    - module: mpi/openmpi-x86_64
      mpi_packages: "openmpi openmpi-devel"
      env_vars: |
        setenv OMPI_MCA_pml ob1
        setenv OMPI_MCA_btl tcp,self
    - module: mpi/mpich-x86_64
      mpi_packages: "mpich mpich-devel"
      env_vars: ""
  loop_control:
    loop_var: mpi
  when: "'clients' in group_names"

