---
- name: Load consolidated OS variables
  include_vars: "../vars/mpi_{{ ansible_os_family }}.yml"

- name: Install OSU micro_benchmarks with each MPI
  include_tasks: ../tasks/install_osu_micro_benchmarks.yaml
  loop: "{{ mpi_implementations }}" 
  loop_control:
    loop_var: mpi_implementation
