---
- name: Run IO500 using all MPI implementations 
  hosts: clients
  gather_facts: true
  become: false

  tasks:
    - name: Run IO500 on just the lead client 
      when: inventory_hostname == groups['clients'][0]
      block:
        - name: Gather only the OS family fact
          ansible.builtin.setup:

        - name: Load OS-specific variables
          ansible.builtin.include_vars: "../vars/mpi_{{ ansible_os_family }}.yml"

        - name: Load IO500 variables
          ansible.builtin.include_vars: "../vars/io500.yaml"

        - name: Run IO500 tests for multiple MPI implementations
          ansible.builtin.include_tasks: run_io500.yaml
          loop: "{{ mpi_implementations }}"
          loop_control:
            loop_var: mpi_config
          register: io500_task_results
      # Enforce execution strictly on the first host of the clients group
