---
- name: Hello World Playbook
  hosts: clients
  gather_facts: false
  tasks:
  - name: Run IOR on clients using mpirun with delegated tasks
    block:
      - name: Count the hosts in the clients group
        set_fact:
          client_count: "{{ groups['clients'] | length }}"

      - name: Set IOR parameters as facts
        set_fact:
          hostfile:         "/tmp/hosts.{{ UNIQUE_TAG }}"
          segmentCount:     16       
          transferSize:     1048576   
          blockSize:        10485760        
          summaryFormat:    "JSON"
          summaryFile:      "/tmp/ior_{{ UNIQUE_TAG }}.json"

      - name: Set fstype based on UNIQUE_TAG
        set_fact:
          fstype: "{{ 'lustre' if UNIQUE_TAG == 'l2154p1' else 'beegfs' if UNIQUE_TAG == 'beegfs743' else undef(hint='Invalid or missing UNIQUE_TAG') }}"

      - name: Set outputPath using fstype and UNIQUE_TAG
        set_fact:
          outputPath: "/mnt/{{ fstype }}/ior.{{ UNIQUE_TAG }}"

      - name: Write the list of client hostnames to the hostfile
        copy:
          content: "{{ groups['clients'] | join('\n') }}"
          dest: "{{ hostfile }}"

      - name: Run IOR tests for multiple MPI implementations
        vars:
          mpi_configs:
            - mpi_module: mpi/mpich-x86_64
              mpirun_args: ""
            - mpi_module: mpi/openmpi-x86_64
              mpirun_args: "--allow-run-as-root --prefix $MPI_HOME"
        include_tasks: run_ior.yaml
        loop: "{{ mpi_configs }}"
        loop_control:
          loop_var: mpi_config
    delegate_to: "{{ groups['clients'][0] }}"
    run_once: true
