- name: Wait for SSH and use virsh to restart if wait times-out 
  block:
    - name: Increment the retry count
      set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"
        max_retries: 5

    - name: Attempt to wait for SSH port to be ready
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 10
        timeout: 400
        state: started
      delegate_to: localhost

  rescue:
    - fail:
        msg: Maximum retries of ssh reached
      when: retry_count | int == max_retries

    - debug:
        msg: "Task Group failed, let's give it another shot. Attempt {{ retry_count }} of {{ max_retries }}"

    # the below items won't work because the VM isn't running on localhost but it's running on it's own physical host
    - block:
      - name: Check if VM is running
        command: virsh domstate {{ inventory_hostname }}
        register: vm_state

      - name: Restart VM using virsh if running and first time through loop
        command: virsh reboot {{ inventory_hostname }}
        when: vm_state.stdout.strip() == 'running' and retry_count | int == 0

      - name: Start VM using virsh if not running 
        command: virsh start {{ inventory_hostname }}
        when: vm_state.stdout.strip() != 'running' 
      ignore_errors: true
      delegate_to: localhost

    - name: Sleep for 60 seconds on each host independently
      command: sleep 60

    - include_tasks: retry_ssh.yaml
