- name: Define OSU benchmark executables
  set_fact:
    osu_benchmarks:
      - mpi/startup/osu_hello
      - mpi/pt2pt/osu_latency
      - mpi/pt2pt/osu_bw
      - mpi/collective/osu_allreduce
      - mpi/collective/osu_alltoall
      - mpi/one-sided/osu_get_latency
      - mpi/one-sided/osu_put_bw

- name: Run OSU benchmarks for {{ mpi_config.mpi_module }}
  include_tasks: run_single_osu.yaml
  loop: "{{ osu_benchmarks }}"
  loop_control:
    loop_var: osu_exe

