---
- name: Configure Lustre on all nodes 
  hosts: all
  become: true
  gather_facts: no
  max_fail_percentage: 0  # Abort immediately if any host fails
  tasks:
    - include_tasks: configure_variables.yaml

    - name: Ensure marker directory exists 
      include_tasks: ../../shared/ensure_marker_dir.yaml

    - name: Gather facts
      setup:

    - include_tasks: ../../shared/set_hostname.yaml

    - name: Configure passwordless ssh 
      include_tasks: ../../shared/configure_ssh.yaml

    - name: Configure Lustre
      include_tasks: configure_lustre.yaml
