---
- name: Configure Lustre on all nodes 
  hosts: all
  become: true
  gather_facts: true
  max_fail_percentage: 0  # Abort immediately if any host fails
  tasks:
    - include_tasks: configure_variables.yaml

    - name: Ensure marker directory exists 
      include_tasks: ../../shared/ensure_marker_dir.yaml

    - name: Gather facts
      setup:

    - name: Check if Python 3.11 exists
      stat:
        path: /usr/bin/python3.11
      register: py311

    - name: Use Python 3.11 for Ansible if available
      set_fact:
        ansible_python_interpreter: /usr/bin/python3.11
      when: py311.stat.exists

    - include_tasks: ../../shared/set_hostname.yaml

    - name: Configure passwordless ssh 
      include_tasks: ../../shared/configure_ssh.yaml

    - name: Configure Lustre
      include_tasks: configure_lustre.yaml
