- name: Gather service facts
  service_facts:
  tags:
    - config
    - firewall

- name: Fail if firewalld service is running
  fail:
    msg: "Firewalld service is running and must be stopped."
  when: "'firewalld' in ansible_facts.services and ansible_facts.services.firewalld.state == 'running'"
  tags:
    - config
    - firewall

- name: Check SELinux status
  command: getenforce
  register: selinux_status
  changed_when: false
  tags:
    - selinux
    - lustre
    - config
    - precheck

- name: Verify SELinux is disabled
  assert:
    that:
      - selinux_status.stdout == "Disabled"
    fail_msg: "Error: SELinux is not disabled. Current status is {{ selinux_status.stdout }}"
  tags:
    - selinux
    - lustre
    - config
    - precheck

- name: Load ZFS kernel module
  modprobe:
    name: zfs
    state: present
  when: "'clients' not in group_names"
  register: zfs_module_loaded
  changed_when: zfs_module_loaded is changed
  tags:
    - configure
    - zfs
    - modules

- name: Ensure ZFS kernel module is loaded on reboot
  copy:
    dest: /etc/modules-load.d/zfs.conf
    content: |
      # Load ZFS module on boot
      zfs
  when: "'clients' not in group_names"
  register: zfs_module_config
  changed_when: zfs_module_config is changed
  tags:
    - configure
    - zfs
    - modules

- name: Rebuild module dependency map after ZFS modules loaded
  command: depmod -a
  when: (zfs_module_loaded.changed or zfs_module_config.changed) and "'clients' not in group_names"
  tags:
    - configure
    - modules
    - lustre
    - zfs

- name: Pick the effective IP for this host
  set_fact:
    node_ip: >-
      {{ mvpnet_ip
         if (networking is defined and networking == 'mvpnet' and (mvpnet_ip is defined))
         else node_ip }}
  when: false # do I need to repeat this here?

- name: Debug {{ node_ip }} for {{ hostname }}
  debug:
    var: node_ip

- name: Extract the last octet of the IP address
  set_fact:
    ip: "{{ node_ip.split('.')[-1] }}"

- name: Extract the first three octets of the IP address
  set_fact:
    network_addr: "{{ node_ip | regex_replace('\\.\\d+$', '') }}"

- name: Debug IP and Network Address
  debug:
    msg: "IP: {{ ip }}, Network Addr: {{ network_addr }}"

- block:
  - name: Construct the IP address
    set_fact:
      node_ip: "{{ network_addr }}.{{ ip }}"

  - name: Query the interface name
    shell: "ip -o -4 addr show | awk '/{{ node_ip }}/{print $2}'"
    register: interface_name
    changed_when: false

  - name: Gather all IP addresses
    set_fact:
      all_ips: "{{ groups['all'] | map('extract', hostvars, 'ip') | list }}"
    run_once: true
  tags: 
    - configure
    - modules
    - lustre

- block:
  - name: Dynamically construct the modprobe_opts variable
    set_fact:
      modprobe_opts: "options lnet ip2nets=\"tcp0({{ interface_name.stdout }}) {{ network_addr }}.[{{ all_ips | join(',') }}]\"\n"

  - name: Debug the modprobe_opts value
    debug:
      var: modprobe_opts

  - name: Write the modprobe_opts value to /etc/modprobe.d/lustre.conf
    copy:
      dest: /etc/modprobe.d/lustre.conf
      content: "{{ modprobe_opts }}"
      mode: 0644
  tags: 
    - configure
    - modules
    - lustre

- name: Reconfigure LNet for mvpnet
  when: networking == "mvpnet"
  block:
    - name: Unconfigure LNet
      ansible.builtin.command: lnetctl lnet unconfigure
      ignore_errors: true

    - name: Load lnet kernel module
      ansible.builtin.command: modprobe lnet

    - name: Configure LNet
      ansible.builtin.command: lnetctl lnet configure

    - name: Remove existing tcp0 network if present
      ansible.builtin.command: lnetctl net del --net tcp0
      ignore_errors: true
      register: remove_tcp0
      changed_when: "'deleted' in remove_tcp0.stdout or remove_tcp0.rc == 0"

    - name: Add tcp0 network interface
      ansible.builtin.command: "lnetctl net add --net tcp0 --if {{ device }}"

- block:
  - name: Load Lustre modules
    modprobe:
      name: "{{ item }}"
      state: present
    loop:
      - ksocklnd
      - lustre
    register: lustre_modules_loaded
    changed_when: lustre_modules_loaded is changed

  - name: Ensure Lustre modules are loaded on reboot
    copy:
      dest: /etc/modules-load.d/lustre.conf
      content: |
        # Load Lustre modules on boot
        ksocklnd
        lustre
    register: lustre_modules_config
    changed_when: lustre_modules_config is changed

  - name: Rebuild module dependency map after Lustre modules loaded
    command: depmod -a
    when: (lustre_modules_loaded.changed or lustre_modules_config.changed)
  tags:
    - configure
    - modules
    - lustre

- name: Verify {{ module_name }} module is loaded
  command: lsmod
  register: lsmod_output
  failed_when: "module_name not in lsmod_output.stdout"
  no_log: no
  loop:
    - lustre
    - zfs
  loop_control:
    loop_var: module_name
  tags:
    - modules
    - lustre
    - config
  when: "'servers' in group_names"

- name: Unmount client mounts 
  ansible.builtin.mount:
    path: "{{ item }}"
    state: unmounted
  with_items: "{{ target_mount }}"
  when: 
    - target_mount is defined
    - "'clients' in group_names"

- name: Unmount OSS and MDS mounts 
  ansible.builtin.mount:
    path: "{{ item }}"
    state: unmounted
  with_items: "{{ target_mount }}"
  when: 
    - target_mount is defined
    - "'clients' not in group_names"

- name: Unmount MGS mount 
  ansible.builtin.mount:
    path: "{{ item }}"
    state: unmounted
  with_items: "{{ mgt_mount }}"
  when: mgt_mount is defined

- name: Stop Lustre service
  ansible.builtin.systemd:
    name: lustre
    state: stopped
  when: "'clients' not in group_names"

- name: Stop LNet service
  ansible.builtin.systemd:
    name: lnet
    state: stopped

# would be nice if this one didn't destroy all but just destroyed the ones created later
- name: Destroy all ZFS pools
  ansible.builtin.shell: |
    for pool in $(zpool list -H -o name); do
      zpool destroy $pool
    done
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: zpool_destroy
  when: "'clients' not in group_names"

- name: Clear ZFS labels from all zpool disks
  ansible.builtin.shell: |
    for disk in $(zpool list -H -o name); do
      zpool labelclear -f /dev/disk/by-id/$disk
    done
  args:
    executable: /bin/bash
  when: 
    - "'clients' not in group_names"
    - zpool_destroy is succeeded

- name: List all disks and partitions
  ansible.builtin.shell: lsblk -nro NAME
  register: disks
  ignore_errors: yes
  when: "'clients' not in group_names"

- name: Clear ZFS labels from all disks and partitions
  ansible.builtin.shell: |
    for disk in $(echo '{{ disks.stdout }}'); do
      zpool labelclear -f /dev/$disk
    done
  args:
    executable: /bin/bash
  ignore_errors: yes # some are not zpools
  when: 
    - "'clients' not in group_names"
    - disks.stdout != ""

- name: Remove mgs mount points if they exist
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ mgt_mount }}"
  when: mgt_mount is defined

- name: Remove mds and oss and client mount points if they exist
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ target_mount }}"
  when: target_mount is defined

- block:
  - name: Set target_disk fact for first server disk based on networking type
    ansible.builtin.set_fact:
      target_disk: >-
        {% if networking == 'mvpnet' %}
        /dev/vdc
        {% else %}
        /dev/disk/by-id/virtio-{{ ansible_hostname }}.b
        {% endif %}
    changed_when: false

  - name: Find the full path of the OST and MDT devices
    ansible.builtin.shell: "ls {{ target_disk }}"
    register: device_path
    changed_when: false

  - name: Create ZFS pools for osts and mdts
    ansible.builtin.command: 
      cmd: "zpool create {{ ansible_hostname }} {{ device_path.stdout }}"
    args:
      creates: "/dev/zvol/{{ ansible_hostname }}"
    when: 
      - device_path.stdout != ""
  when: "'clients' not in group_names"

- block:
  - name: Set target_disk fact for mgs device based on networking type
    ansible.builtin.set_fact:
      mgs_disk: >-
        {% if networking == 'mvpnet' %}
        /dev/vdd
        {% else %}
        /dev/disk/by-id/virtio-{{ ansible_hostname }}.c
        {% endif %}
    changed_when: false

  - name: Find the full path of the mgs device 
    ansible.builtin.shell: "ls {{ mgs_disk }}"
    register: mgs_device_path
    changed_when: false

  - name: Create ZFS pool for mgt 
    ansible.builtin.command: 
      cmd: "zpool create {{ mgt_target }} {{ mgs_device_path.stdout }}"
    args:
      creates: "/dev/zvol/{{ mgt_target }}"

  - name: Create Lustre filesystem on MGS
    ansible.builtin.command:
      cmd: "mkfs.lustre --mgs --backfstype=zfs --fsname=lustre {{ mgt_target }}/mgt"
  when: mgt_target is defined

- name: Generate host ID for all hosts
  ansible.builtin.command: genhostid
  register: genhostid_result
  changed_when: "'Host ID set to' in genhostid_result.stdout"

- block:
  - name: Set mkfs.lustre command as a fact
    ansible.builtin.set_fact:
      mkfs_command: >
        mkfs.lustre --reformat
        --{{ target_type }}
        --mgsnode={{ mgs_node }}
        --failnode={{ failnode }}@tcp
        --backfstype=zfs
        --fsname=lustre
        --index={{ index }}
        {{ target }}

  - name: Debug mkfs.lustre command before execution
    ansible.builtin.debug:
      var: mkfs_command

  - name: Run mkfs.lustre command
    ansible.builtin.command:
      cmd: "{{ mkfs_command }}"
    register: mkfs_output

  - name: Debug mkfs.lustre output
    debug:
      var: mkfs_output.stdout
    tags:
      - debug
  when:
    - "'clients' not in group_names"
    - target is defined
  tags:
    - configure
    - lustre

- name: Create MDS and OSS and client mount points
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ target_mount }}"
  when: target_mount is defined
  tags:
    - configure
    - lustre

- name: Create MGS mount point
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ mgt_mount }}"
  when: mgt_mount is defined
  tags:
    - configure
    - lustre

- name: Start LNet service
  ansible.builtin.systemd:
    name: lnet
    state: started
    enabled: yes
  tags:
    - configure
    - lustre


- block:
  - name: Detect network interface for LNet based on `node_ip`
    ansible.builtin.shell:
      cmd: "ip -o addr show | awk '/{{ node_ip | regex_escape }}/ {print $2; exit}'"
    register: correct_interface
    changed_when: false

  - name: Debug detected interface
    ansible.builtin.debug:
      msg: "LNet should use interface {{ correct_interface.stdout }} (IP: {{ node_ip }})"

### Persist LNet Configuration (Only on MDS and OSS Nodes)**
- block:
    - name: Persist LNet configuration in modprobe
      ansible.builtin.copy:
        dest: "/etc/modprobe.d/lustre.conf"
        content: "options lnet networks=tcp({{ correct_interface.stdout }})\n"
        owner: root
        group: root
        mode: "0644"

    - name: Update initramfs for persistence
      ansible.builtin.command:
        cmd: "dracut -f"

    - name: Ensure LNet service is restarted
      ansible.builtin.systemd:
        name: lnet
        state: restarted
        enabled: yes
  when: "'clients' not in group_names"

# this block removes the lnet interface on the default network and adds one on the storage network
# this must go after the previous because the previous overwrites /etc/modprobe.d/lustre.conf
# this block maybe isn't needed when networking is mvpnet
- block:

  ### Get the Currently Configured LNet Interface**
  - name: Get current LNet interface
    ansible.builtin.shell:
      cmd: "lnetctl net show | awk '/tcp/ {getline; print $3}'"
    register: current_lnet_interface
    changed_when: false
    ignore_errors: yes  # Avoid failure if LNet is not configured

  - name: Debug current LNet interface
    ansible.builtin.debug:
      msg: "Currently configured LNet interface: {{ current_lnet_interface.stdout | default('None') }}"

  ### Remove the Wrong LNet Interface**
  - name: Remove the incorrect LNet interface
    ansible.builtin.command:
      cmd: "lnetctl net del --net tcp"
    when:
      - current_lnet_interface.stdout is defined
      - current_lnet_interface.stdout != correct_interface.stdout
    ignore_errors: yes

  ### Add the Correct LNet Interface**
  - name: Configure LNet to use the correct interface
    ansible.builtin.command:
      cmd: "lnetctl net add --net tcp --if {{ correct_interface.stdout }}"
    when:
      - correct_interface.stdout | length > 0

  ### Debug LNet Configuration After Change**
  - name: Verify LNet configuration after update
    ansible.builtin.command:
      cmd: "lnetctl net show"
    register: lnet_show_output
    changed_when: false

  - name: Debug LNet configuration
    ansible.builtin.debug:
      var: lnet_show_output.stdout_lines

- name: Start Lustre service
  ansible.builtin.systemd:
    name: lustre
    state: started
    enabled: yes
  when: "'clients' not in group_names"
  tags:
    - configure
    - lustre

- name: Check if mount.lustre exists
  stat:
    path: /sbin/mount.lustre
  register: mount_lustre_check
  tags:
    - lustre
    - verify

- name: Fail if mount.lustre is missing
  fail:
    msg: >
      CRITICAL: /sbin/mount.lustre is missing. 
      This likely happened due to a failure in make the gold images.
      make phase1-clean and try again. 
  when: not mount_lustre_check.stat.exists
  tags:
    - lustre
    - verify

- name: Mount MGS target
  ansible.builtin.shell:
    cmd: "mount -t lustre {{ mgt_target }}/mgt {{ mgt_mount }}"
  when: mgt_target is defined and mgt_mount is defined
  tags:
    - configure
    - lustre

- name: Mount MDS and OSS targets
  ansible.builtin.shell:
    cmd: "mount -t lustre {{ target }} {{ target_mount }}"
  when: target is defined and target_mount is defined
  tags:
    - configure
    - lustre

- name: Mount client
  ansible.builtin.shell:
    cmd: "mount -t lustre {{ mgs_node }}:/lustre {{ target_mount }}"
  when: 
    - target_mount is defined 
    - "'clients' in group_names"
  tags:
    - configure
    - lustre
