- name: Set facts for local variables needed
  set_fact:
    zfs_repo: /usr/local/src/zfs

- name: Gather facts
  setup:

- name: Include kernel rpms installation tasks
  include_tasks: install_kernel_rpms.yaml
  tags:
    - zfs

- block:
  - name: Install EPEL repository and ZFS dependencies phase 1
    dnf:
      name:
        # from https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html
        - epel-release
        - gcc
        - make
        - autoconf
        - automake
        - libtool
        - rpm-build
        - kernel-rpm-macros
        - libtirpc-devel
        - libblkid-devel
        - libuuid-devel
        - libudev-devel
        - openssl-devel
        - zlib-devel
        - libaio-devel
        - libattr-devel
        - elfutils-libelf-devel
        - python3
        - python3-devel
        - python3-setuptools
        - python3-cffi
        - libffi-devel
        - ncompress
      enablerepo:
        - epel
      state: present
      skip_broken: true

  - name: Install EPEL repository and ZFS dependencies phase 2
    dnf:
      name:
        - python3-packaging
        - dkms
      enablerepo:
        - epel
        - powertools
      state: present
      skip_broken: true

  - name: Install Git
    dnf:
      name: git
      state: present

  - name: Clone ZFS repository
    git:
      repo: "{{ backend_source_repo }}"
      dest: "{{ zfs_repo }}"
      version: tags/{{ backend_version }} 
      clone: yes
      update: yes
      force: yes
    # some network issue kills the git clone so add retry
    register: git_clone
    until: git_clone is succeeded
    retries: 5
    delay: 10

  - block:
    - name: Copy ZFS patch from control node to worker nodes
      copy:
        src: "{{ backend_patch }}"
        dest: "{{ zfs_repo }}/zfs.patch"

    - name: Apply patch to ZFS source
      shell: |
        cd "{{ zfs_repo }}"
        git apply zfs.patch
    when: backend_patch is defined
    tags:
      - build
      - patch
      - zfs

  - name: Build and install ZFS
    shell: |
      cd "{{ zfs_repo }}"
      ./autogen.sh
      ./configure --with-spec=redhat
      make pkg-utils pkg-kmod
      touch "{{ build_marker }}"
    args:
      executable: /bin/bash
      creates: "{{ build_marker }}"
    vars:
      build_marker: "{{ marker_dir | default('/tmp') }}/build_zfs.marker"

  - name: Find RPM files in zfs installation
    find:
      paths: "{{ zfs_repo }}"
      patterns: "*.{{ ansible_architecture }}.rpm"
    register: rpm_files

  - name: Install ZFS RPMs
    dnf:
      name: "{{ rpm_files.files | map(attribute='path') | list }}"
      state: present
      disable_gpg_check: yes

  - name: Rebuild module dependency map
    shell: depmod -a && touch "{{ build_marker }}"
    args:
      creates: "{{ build_marker }}" 
    vars:
      build_marker: "{{ marker_dir | default('/tmp') }}/depmod_a.marker"
  when: "'oss' in group_names or 'mds' in group_names"

