---
- name: Ensure required variables are set
  set_fact:
    lustre_patch: "/mnt/usrc-storage-nfs/jbent/patches/lustre/test_patch.patch" # comment out this line if no patch
    lustre_source_repo: "git://git.whamcloud.com/fs/lustre-release.git"
    lustre_version: "2.15.4"
    lustre_backfstype: "zfs"
    backend_source_repo: "https://github.com/openzfs/zfs.git"
    backend_version: "zfs-2.1.11"
    backend_patch: "/mnt/usrc-storage-nfs/jbent/patches/zfs/zfs_patch1.patch"  # comment out this line if no patch 
    #mgs_node: '192.168.56.10@tcp:192.168.56.20@tcp' # the old way. These are the first two IP addresses of the MDS nodes 

- name: Ensure marker directory exists
  file:
    path: /var/log/ansible/{{ UNIQUE_TAG }}
    state: directory
    mode: '0755'
  register: marker_dir_status

- set_fact:
    marker_dir: "{{ marker_dir_status.path }}"

- name: Install ZFS
  include_tasks: install_zfs.yaml

- name: Install Lustre
  include_tasks: install_lustre.yaml

- name: Run Final Configuration Steps
  include_tasks: ../../shared/install_tools.yaml
  vars:
    ior_config_option: '--with-lustre'

- name: Disable firewall and SELinux
  include_tasks: ../../shared/disable_firewall_selinux.yaml

