system:
  network: 
    addr: '192.168.56'
    name: 'hostonly-net'
  hosts:
    mds00: 
      ip: '10'
      hds: [5, 5]
    mds01: 
      ip: '20'
      hds: [5]
    oss00: 
      ip: '30'
      hds: [10]
    oss01: 
      ip: '40'
      hds: [10]
    client: 
      ip: '50'
      hds: []

tests: {}

