- name: Install Necessary Software for the Empty Cluster 
  set_fact:
    ior_config_option: '' # no config options for beegfs install 

- name: Ensure marker directory exists 
  include_tasks: ../../shared/ensure_marker_dir.yaml

- include_tasks: ../../shared/tasks/install_environment_modules.yaml

- include_tasks: ../../shared/install_mpi.yaml

- include_tasks: ../../shared/disable_firewall_selinux.yaml

- name: Install and build IOR + MPI Hello
  include_tasks: ../../shared/install_ior.yaml
  loop: "{{ mpi_implementations }}"
  loop_control:
    loop_var: mpi
  when: "'clients' in group_names"

- include_tasks: install_pnfs_actual.yaml 
