- name: Install Necessary Software for the Empty Cluster 
  set_fact:
    ior_config_option: '' # no config options for beegfs install 

- name: Ensure marker directory exists 
  include_tasks: ../../shared/ensure_marker_dir.yaml

- include_tasks: ../../tasks/install_environment_modules.yaml

- include_tasks: ../../shared/install_mpi.yaml

- include_tasks: ../../shared/disable_firewall_selinux.yaml

- name: Discover available MPI modules
  ansible.builtin.include_tasks: ../../tasks/discover_mpi_modules.yaml
  
- name: Install and build IOR + MPI Hello and IO500
  include_tasks: ../../shared/install_ior.yaml
  loop: "{{ available_mpi_modules }}"
  loop_control:
    loop_var: available_mpi_module
    label: "{{ available_mpi_module }}"
  vars:
    mpi:
      module: "{{ available_mpi_module }}"

- include_tasks: install_pnfs_actual.yaml 
