target_ip: >-
  {%- if infiniband_ip is defined and infiniband_ip | trim | length > 0 -%}
    {{ infiniband_ip | trim }}
  {%- elif networking == 'mvpnet' -%}
    {{ mvpnet_ip | trim }}
  {%- elif networking == 'none' -%}
    {{ ansible_default_ipv4.address | trim }}
  {%- else -%}
    {{ ansible_host | default(inventory_hostname) | trim }}
  {%- endif -%}
