target_ip: >-
  {%- if networking == 'mvpnet' -%}
    {{ mvpnet_ip | trim }}
  {%- elif networking == 'none' -%}
    {{ ansible_default_ipv4.address }}
  {%- else -%}
    {{ ansible_host | default(inventory_hostname) | trim }}
  {%- endif -%}
