install_playbook: "tasks/beegfs/install_beegfs_all.yaml"  
kickstart_dir: "/tmp"
vm_directory: "/mnt/usrc-storage-nfs/jbent/images"

vm_definitions:
  defaults: # each default value can be overwritten in the individual entries
    iso: "/mnt/usrc-storage-nfs/jbent/images/alma/AlmaLinux-8.10-x86_64-minimal.iso"
    network:
      bootproto: "dhcp"
      default: "default"
      device: "enp1s0"
      ipv6: "noipv6"
      ntpservers:
        - "0.pool.ntp.org"
        - "1.pool.ntp.org"
        - "2.pool.ntp.org"
        - "3.pool.ntp.org"
      onboot: "yes"
    os_variant: "almalinux8"
    root_pwd: "password"
    ssh_keys: '/home/jbent/.ssh/authorized_keys'
    system:
      type: 'beegfs'
      version: '7.4.3'
      loglevel: '5'
    timezone: "US/Mountain"
  individual:
    - name: gold-beegfs-almalinux8-server
      disk_size: 12
      group: "servers"
      memory: 2048
      vcpu: 2
    - name: gold-beegfs-almalinux8-client
      disk_size: 6
      group: "clients"
      memory: 1024
      vcpu: 1

# create collapsed versions of each individual gold vm inheriting from defaults as necessary
gold_vms: "{{ vm_definitions.individual | map('combine', vm_definitions.defaults) | list }}"
