- name: Save collected data to a JSON file
  copy:
    content: "{{ hostvars | to_json }}"
    dest: /tmp/hostvars.json
  run_once: true
  delegate_to: localhost
  when: true 
  tags: debug

- name: Ensure {{ image_dir }} directory
  ansible.builtin.file:
    path: "{{ image_dir }}"
    state: directory
  delegate_to: localhost
  run_once: true

- name: Remove any previously rendered images from {{ image_dir }}
  ansible.builtin.shell: "rm -f {{ image_dir }}/*.png"
  tags: makeclean

- name: Gather facts from all VMs
  setup:
  delegate_to: "{{ item }}"
  loop: "{{ groups['vms'] }}"
  run_once: true

- name: Create networking graph 
  block:
  - name: Debug key structures
    debug:
      msg:
      - "Host: {{ inventory_hostname }}"
      - "ansible_default_ipv4.address = {{ ansible_default_ipv4.address | default('MISSING') }}"
      - "matching_vms = {{ matching_vms | default('MISSING') }}"
      - "vm_ips = {{ vm_ips | default('MISSING') }}"
     
  - name: Render graph in DOT format
    template:
      src: "{{ template_file }}"
      dest: "{{ image_dir }}/graph.dot"

  - name: Convert DOT file to PNG
    shell: dot -Tpng {{ image_dir }}/graph.dot -o {{ image_dir }}/graph.png
    args:
      executable: /bin/bash
    register: dot_to_png_result
  run_once: true
  delegate_to: localhost

