- name: Save collected data to a JSON file
  copy:
    content: "{{ hostvars | to_json }}"
    dest: /tmp/hostvars.json
  run_once: true
  delegate_to: localhost
  when: true 
  tags: debug

- name: Ensure {{ image_dir }} directory
  ansible.builtin.file:
    path: "{{ image_dir }}"
    state: directory
  delegate_to: localhost
  run_once: true

- name: Remove any previously rendered images from {{ image_dir }}
  ansible.builtin.shell: "rm -f {{ image_dir }}/*.png"
  tags: makeclean

- name: Block of tasks to get networking details when using a dedicated secondary NIC
  block:
  - name: Render graph in DOT format
    template:
      src: "{{ template_file }}"
      dest: "{{ image_dir }}/graph.dot"

  - name: Convert DOT file to PNG
    shell: dot -Tpng {{ image_dir }}/graph.dot -o {{ image_dir }}/graph.png
    args:
      executable: /bin/bash
    register: dot_to_png_result
  run_once: true
  delegate_to: localhost

