# Ansible Playbook for Dynamic Network Graph and Validation
- hosts: physical_hosts
  gather_facts: yes
  any_errors_fatal: true
  become: false
  vars:
    ping_count: 3
    ansible_remote_tmp: /tmp

  tasks:
    - block:
      - name: Remove {{ image_dir }}
        ansible.builtin.file:
          path: "{{ image_dir }}"
          state: absent
        delegate_to: localhost
        run_once: true
        when: true # clean up image dir

      - name: Exit after cleanup
        ansible.builtin.meta: end_play
        when: "'makeclean' in ansible_run_tags"
      tags: makeclean

    - name: Network Testing
      block:
      - name: Fail if network.type is not defined
        fail:
          msg: "'network.type' must be defined"
        when: network.type is not defined

      - name: Fail if network.type is unsupported
        fail:
          msg: "'network.type' must be either 'private' 'wireguard' or 'mvpnet'. Got: {{ network.type }}"
        when: network.type is defined and network.type not in ['private', 'wireguard', 'mvpnet']

      - name: Create artifacts directory {{ image_dir }}
        ansible.builtin.file:
          path: "{{ image_dir }}"
          state: directory
        delegate_to: localhost
        run_once: true

      - name: Debug network type "{{ network.type }}"
        debug:
          var: network.type

      - name: include private network playbook
        include_tasks: test_private.yaml
        when: network.type == 'private' or network.type == 'mvpnet'

      - name: include wireguard network playbook
        when: network.type == 'wireguard'
        include_tasks: test_wireguard.yaml
      tags: always

    # Add VMs to inventory simply when networking is not mvpnet
    - name: Add VMs to inventory
      add_host:
        name: "{{ item }}"  # Add each VM hostname
        groups: "dynamic_hosts"  # Assign to dynamic_hosts group
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"  
      with_items: "{{ aggregated_matching_vms }}"
      delegate_to: localhost
      run_once: true
      when: network.type != 'mvpnet'

    # Add VMs to inventory a bit more complexly when networking is mvpnet
    - name: Add VMs to inventory
      add_host:
        name: "{{ item }}"  # Add each VM hostname
        groups: "dynamic_hosts"  # Assign to dynamic_hosts group
        ansible_host: "127.0.0.1"                       # the VM is on localhost *from the bastion's POV*
        ansible_port: "{{ hostvars[item].mvpnet_port }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump={{ hostvars[item].physical_host }}"
      with_items: "{{ aggregated_matching_vms }}"
      delegate_to: localhost
      run_once: true
      when: network.type == 'mvpnet'

- name: Run tasks now on the VMs themselves (dynamic_hosts group)
  hosts: vms
  gather_facts: no
  become: true
  vars:
    network: "{{ hostvars[groups['physical_hosts'][0]].network | default(omit) }}"
    ansible_remote_tmp: /tmp
  tasks:
    - debug:
        msg: "Hostname: {{ inventory_hostname }}"
    
    - name: Get MAC addresses when network is mvpnet
      block:
      - name: Gather network facts
        ansible.builtin.setup:
          gather_subset:
            - network

      - name: Pick first physical host
        ansible.builtin.set_fact:
          _phys0: "{{ (groups['physical_hosts'] | default([])) | first | default('') }}"

      - name: Debug chosen _phys0
        ansible.builtin.debug:
          var: _phys0

      - name: Debug network dict on _phys0
        ansible.builtin.debug:
          var: hostvars[_phys0]['network']

      - name: Set target_device from canonical host
        ansible.builtin.set_fact:
          target_device: "{{ hostvars[_phys0]['network']['device'] }}"

      - name: Debug target device 
        ansible.builtin.debug:
          var: target_device 

      - name: Extract MAC/IP from facts
        ansible.builtin.set_fact:
          _iface: "{{ lookup('vars', 'ansible_' ~ target_device) | default({}) }}"
          target_mac: "{{ (_iface.macaddress | default('')) | lower }}"
          target_ipv4: "{{ _iface.ipv4.address | default('') }}"
        when: false

      - name: Query the MAC address 
        ansible.builtin.command: "cat /sys/class/net/{{ target_device }}/address"
        register: _mac_out
        changed_when: false

      - name: Query the IP address
        ansible.builtin.shell: "ip -o -4 addr show dev {{ target_device }} | awk '{print $4}' | cut -d/ -f1"
        register: _ip4_out
        changed_when: false

      - name: Record IP and MAC addreses
        ansible.builtin.set_fact:
          target_mac: "{{ (_mac_out.stdout|trim|lower) }}"
          target_ipv4: "{{ (_ip4_out.stdout|trim) }}"

      - name: Debug {{ target_device }} MAC/IP
        ansible.builtin.debug:
          msg: "Host {{ inventory_hostname }}  iface={{ target_device }}  MAC={{ target_mac | default('UNKNOWN') }}  IPv4={{ target_ipv4 | default('NONE') }}"
      when: network.type == 'mvpnet'

    - name: Re-initialize ping results
      set_fact:
        ping_results: []

    - block:
      - name: All VMs ping each other 
        ansible.builtin.shell: |
          ping -c {{ ping_count | default(3) }} {{ item }}
        # to get list of other vms, use aggregated_matching_vms from the first in the list of original hosts
        with_items: >-
          {{
            hostvars[
              (groups['all'] | difference(groups['dynamic_hosts']) | first)
            ].aggregated_matching_vms
            | difference([inventory_hostname])  
          }}
        register: vm_vm_ping_results 
        ignore_errors: yes
          #when: >
          #(
          #  hostvars[
          #    (groups['all'] | difference(groups['dynamic_hosts']) | first)
          #  ].aggregated_matching_vms
          #  | length
          #) < 20

      - name: Record VM-VM ping results 
        include_tasks: record_ping_results.yaml
        vars:
          ping_results_data: "{{  vm_vm_ping_results.results }}"
          dont_use_ip: true

      - name: Create the graphs
        become: false
        delegate_to: localhost
        run_once: true
        block:
        - name: Make network graph
          include_tasks: make_network_graph.yaml
          vars:
            template_file: templates/network_graph.dot.j2
        - block:
          - name: Aggregate vm-vm ping results
            ansible.builtin.set_fact:
              aggregated_ping_results: >-
                {{
                  ansible_play_hosts_all
                  | map('extract', hostvars, 'ping_results')
                  | sum(start=[])
                }}

          - name: Debug vm-vm ping results
            debug:
              var: aggregated_ping_results

          - name: Render ping results in DOT format
            ansible.builtin.template:
              src: templates/ping_results_vm_vm.dot.j2
              dest: "{{ image_dir }}/ping_results_vm_vm.dot"

          - name: Convert DOT file to PNG in {{ image_dir }}
            ansible.builtin.shell: |
              dot -Kcirco -Tpng "{{ image_dir }}"/ping_results_vm_vm.dot -o "{{ image_dir }}"/ping_results_vm_vm.png
        when: ansible_play_hosts | length < 17

    - name: Message final status
      debug:
        msg: "Graphs of network structure and status now available in {{ image_dir }}"

