# Ansible Playbook for Dynamic Network Graph and Validation
- hosts: physical_hosts
  gather_facts: yes
  any_errors_fatal: true
  vars:
    ping_count: 3

  tasks:
    - block:
      - name: Remove {{ image_dir }}
        ansible.builtin.file:
          path: "{{ image_dir }}"
          state: absent
        when: false # don't clean up image dir

      - name: Exit after cleanup
        ansible.builtin.meta: end_play
        when: "'makeclean' in ansible_run_tags"
      tags: makeclean

    - name: Network Testing
      block:
      - name: Fail if network.type is not defined
        fail:
          msg: "'network.type' must be defined"
        when: network.type is not defined

      - name: Fail if network.type is unsupported
        fail:
          msg: "'network.type' must be either 'private' or 'wireguard'. Got: {{ network.type }}"
        when: network.type is defined and network.type not in ['private', 'wireguard']

      - name: Create artifacts directory {{ image_dir }}
        ansible.builtin.file:
          path: "{{ image_dir }}"
          state: directory
        delegate_to: localhost
        run_once: true

      - name: include private network playbook
        include_tasks: test_private.yaml
        when: network.type == 'private'

      - name: include wireguard network playbook
        when: network.type == 'wireguard'
        include_tasks: test_wireguard.yaml
      tags: always

    # Add VMs to inventory
    - name: Add VMs to inventory
      add_host:
        name: "{{ item }}"  # Add each VM hostname
        groups: "dynamic_hosts"  # Assign to dynamic_hosts group
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"  
      with_items: "{{ aggregated_matching_vms }}"
      delegate_to: localhost
      run_once: true

- name: Verify dynamic_hosts group
  hosts: dynamic_hosts
  gather_facts: no
  tasks:
    - debug:
        msg: "Hostname: {{ inventory_hostname }}"

    - name: Re-initialize ping results
      set_fact:
        ping_results: []

    - name: All VMs ping each other 
      ansible.builtin.shell: |
        ping -c {{ ping_count | default(3) }} {{ item }}
      # to get list of other vms, use aggregated_matching_vms from the first in the list of original hosts
      with_items: >-
        {{
          hostvars[
            (groups['all'] | difference(groups['dynamic_hosts']) | first)
          ].aggregated_matching_vms
          | difference([inventory_hostname])  
        }}
      register: vm_vm_ping_results 
      ignore_errors: yes

    - name: Record VM-VM ping results 
      include_tasks: record_ping_results.yaml
      vars:
        ping_results_data: "{{  vm_vm_ping_results.results }}"
        dont_use_ip: true

    - name: Aggregate vm-vm ping results
      ansible.builtin.set_fact:
        aggregated_ping_results: >-
          {{
            ansible_play_hosts_all
            | map('extract', hostvars, 'ping_results')
            | sum(start=[])
          }}
      delegate_to: localhost
      run_once: true

    - name: Debug vm-vm ping results
      block:
      - name:
        debug:
          var: aggregated_ping_results

      - name: Render ping results in DOT format
        ansible.builtin.template:
          src: templates/ping_results_vm_vm.dot.j2
          dest: "{{ image_dir }}/ping_results_vm_vm.dot"

      # Convert DOT file to PNG
      - name: Convert DOT file to PNG in {{ image_dir }}
        ansible.builtin.shell: |
          dot -Kcirco -Tpng "{{ image_dir }}"/ping_results_vm_vm.dot -o "{{ image_dir }}"/ping_results_vm_vm.png
      delegate_to: localhost
      run_once: true

    - name: Message final status
      debug:
        msg: "Graphs of network structure and status now available in {{ image_dir }}"
      delegate_to: localhost
      run_once: true

