- name: Set network testing facts
  set_fact:
    testing_with_fake_peer: false   # we have three nodes now!
    FAKE_ENDPOINT: "192.192.192.192:51820"
    FAKE_ALLOWED_IPS: "192.192.192.0/24"

- name: Collect network information
  include_tasks: collect_network_info.yaml

- name: Save collected data to a JSON file
  copy:
    content: "{{ hostvars | to_json }}"
    dest: /tmp/hostvars.json
  run_once: true
  delegate_to: localhost
  when: true 
  tags: debug

- name: Ensure {{ image_dir }} directory
  ansible.builtin.file:
    path: "{{ image_dir }}"
    state: directory
  delegate_to: localhost
  run_once: true

- name: Remove any previously rendered images from {{ image_dir }}
  ansible.builtin.shell: "rm -f {{ image_dir }}/*.png"
  tags: makeclean

- name: Render graph in DOT format
  template:
    src: templates/graph.dot.j2
    dest: "{{ image_dir }}/graph.dot"
  run_once: true
  delegate_to: localhost

- name: Convert DOT file to PNG
  shell: dot -Tpng {{ image_dir }}/graph.dot -o {{ image_dir }}/graph.png
  args:
    executable: /bin/bash
  register: dot_to_png_result
  run_once: true
  delegate_to: localhost

- name: Initialize ping results
  set_fact:
    ping_results: []

# Local pings
- name: Ping the bridge interface on each host (local)
  ansible.builtin.shell: |
    ping -c {{ ping_count }} {{ hostvars[inventory_hostname].bridge_ip }}
  register: bridge_ping_results

- name: Record bridge ping result
  set_fact:
    ping_results: >-
      {{
        ping_results + [{
          'src': ansible_default_ipv4.address,
          'dst': hostvars[inventory_hostname].bridge_ip,
          'success': (bridge_ping_results.rc == 0)
        }]
      }}

- name: Ping VMs on the same host by IP address (local)
  ansible.builtin.shell: |
    ping -c {{ ping_count }} {{ item }}
  with_items: "{{ hostvars[inventory_hostname].vm_ips }}"
  register: vm_local_ping_results
  ignore_errors: yes

- name: Record VM ping results by IP
  include_tasks: record_ping_results.yaml
  vars:
    ping_results_data: "{{ vm_local_ping_results.results }}"

- name: Ping VMs on the same host by hostname (local)
  ansible.builtin.shell: |
    ping -c {{ ping_count }} {{ item }}
  with_items: "{{ matching_vms }}"
  register: vm_local_hostname_ping_results
  ignore_errors: yes

- name: Record VM ping results by hostname
  include_tasks: record_ping_results.yaml
  vars:
    ping_results_data: "{{ vm_local_hostname_ping_results.results }}"

- name: Ping bridges on other hosts (remote)
  ansible.builtin.shell: |
    ping -c {{ ping_count }} {{ item }}
  with_items: "{{ groups['physical_hosts'] | map('extract', hostvars, 'bridge_ip') | difference([hostvars[inventory_hostname].bridge_ip]) }}"
  register: bridge_peer_ping_results

- name: Record bridge ping results for other hosts
  include_tasks: record_ping_results.yaml
  vars:
    ping_results_data: "{{ bridge_peer_ping_results.results }}"

- name: Ping VMs on other hosts by IP address (remote)
  ansible.builtin.shell: |
    ping -c {{ ping_count }} {{ item }}
  with_items: >-
    {{
      groups['physical_hosts']
      | map('extract', hostvars, 'vm_ips')
      | map('dict2items')
      | sum(start=[])
      | map(attribute='value')
      | list
      | difference(
          hostvars[inventory_hostname].vm_ips | dict2items | map(attribute='value') | list
        )
    }}
  register: vm_peer_ping_results
  ignore_errors: yes


- name: Record VM ping results for other hosts by IP address
  include_tasks: record_ping_results.yaml
  vars:
    ping_results_data: "{{ vm_peer_ping_results.results }}"

- name: Ping VMs on other hosts by hostname (remote)
  ansible.builtin.shell: |
    ping -c {{ ping_count }} {{ item }}
  with_items: >-
    {{
      groups['physical_hosts']
      | map('extract', hostvars, 'matching_vms')
      | sum(start=[])
      | difference(hostvars[inventory_hostname].matching_vms)
    }}
  register: vm_peer_hostname_ping_results
  ignore_errors: yes

- name: Record VM ping results for other hosts by hostname
  include_tasks: record_ping_results.yaml
  vars:
    ping_results_data: "{{ vm_peer_hostname_ping_results.results }}"

- name: Aggregate and graph ping results
  ansible.builtin.include_tasks: graph_physical_pings.yaml
