# pass state: running to get just running VMs
- name: List all VMs
  community.libvirt.virt:
    command: list_vms
  register: all_vms
  become: true

- name: Set fact if VM exists
  set_fact:
    vm_exists: "{{ item.name in all_vms.list_vms }}"

- block:
  - name: Check if VM {{ item.name }} is running
    community.libvirt.virt:
      name: "{{ item.name }}"
      command: list_vms
      state: running
      uri: qemu:///system
    register: running_vms
    check_mode: no

  - name: Shut down VM {{ item.name }} if running
    community.libvirt.virt:
      name: "{{ item.name }}"
      state: shutdown
      uri: qemu:///system
    register: shutdown_result
    when: item.name in running_vms.list_vms 

  - name: Wait for VM {{ item.name }} to shut down
    community.libvirt.virt:
      command: list_vms
      state: shutdown
      uri: qemu:///system
    register: vm_state
    until: item.name in vm_state.list_vms
    retries: 10
    delay: 5
    when: not ansible_check_mode # this fails in --check mode so disable it

  # unfortunately this extra task is required since the ansible virt module doesn't have an option to remove disks
  - name: Undefine VM {{ item.name }} and remove disks
    command: "virsh undefine {{ item.name }} --remove-all-storage"
    ignore_errors: yes
    when: vm_exists

  - name: Delete VM {{ item.name }}
    virt:
      name: "{{ item.name }}"
      state: destroyed
      uri: qemu:///system
      force: true
    ignore_errors: yes # might fail because the previous command might have already finished
  when: vm_exists
  become: true  # need to be root for the virsh stuff

- name: Delete QCOW2 image for VM {{ item.name }}
  file:
    path: "{{ item.qcow_file }}"
    state: absent
