- name: Run install tasks directly on the bare metal physical nodes
  hosts: all
  become: true
  any_errors_fatal: true

  tasks:
    - name: Include install tasks
      include_tasks: "../../../{{ install_playbook }}" 
