- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hostname
  lineinfile:
    path: /etc/hostname
    line: "{{ inventory_hostname }}"

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^(127\\.0\\.1\\.1\\s+).*'
    line: "127.0.1.1 {{ inventory_hostname }}"
    state: present
    backup: yes

- name: Verify /etc/hosts update
  shell: "grep '^127\\.0\\.1\\.1\\s{{ inventory_hostname }}$' /etc/hosts"
  register: grep_result
  ignore_errors: yes

- name: Fail if /etc/hosts update did not work
  fail:
    msg: "/etc/hosts update failed"
  when: grep_result.rc != 0

- name: Reboot the machine to apply hostname changes
  ansible.builtin.reboot:
