#!/usr/bin/env python3
"""Generate the short-stonewall IO500 configuration screening matrix."""

from pathlib import Path


OUTPUT_DIR = Path(__file__).with_name("pnfs_io500_phase1")
PPNS = (1, 8, 16, 32)
STRIPE_SIZE_SCREENING_BYTES = (4194304, 16777216, 67108864)
VARIANTS = (
    ("rdma", True),
    ("rdma", False),
    ("tcp", True),
    ("tcp", False),
)

CONFIG = """\
# Generated by configs/xem/generate_pnfs_io500_phase1.py.
all:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    current_user: "{{{{ lookup('env', 'USER') }}}}"
    host_domain: "{{{{ current_user }}}}.mvpnet"
    result_dir: '/proj/mvpnet/{{{{ current_user }}}}/experiments'
    local_storage: /mnt/local
    network:
      type: 'none'
    output_dir: "/tmp/{{{{ current_user }}}}/experiments"
    playbooks:
      bootstrap_cluster: "./playbooks/shared/prereqs.yaml"
      gold_install: "./playbooks/pnfs/install_golds/install_pnfs_all.yaml"
      cluster_config: "./playbooks/pnfs/configure_cluster/configure_pnfs_monolithic.yaml"
      cluster_test: "./playbooks/shared/io500_tester.yaml"
    system:
      type: 'pnfs'
      version: 'xx'
      pnfs_src: '/proj/mvpnet/jbent/pnfs-lattice/'
      rondb_url: 'https://repo.hops.works/master/rondb-26.02.4-linux-glibc2.28-x86_64.tar.gz'
      ds_transport: '{transport}'
      client_mds_assignment: '{client_mds_assignment}'
      stripe_width: {stripe_width}
      stripe_size: {stripe_size}
      hpc_serve_layouts: true
    io500:
      stonewall_time: 30
      ppn: {ppn}
      result_metadata:
        mdsassign: "{{{{ system.client_mds_assignment }}}}"
      data_directory_xattrs:
        - name: user.pnfs.hpc_shared
          value: "{{{{ '1' if system.stripe_width | int > 1 else '0' }}}}"
    UNIQUE_TAG: "pmanual"

  children:
    physical_hosts:
      vars:
        ansible_host: "{{{{ inventory_hostname }}}}.{{{{ host_domain }}}}"
      children:
        ds:
          hosts:
            ds0:
            ds1:
            ds2:
            ds3:
            ds4:
            ds5:
            ds6:
            ds7:
            ds8:
            ds9:
        clients:
          hosts:
            cli0:
            cli1:
            cli2:
            cli3:
            cli4:
            cli5:
            cli6:
            cli7:
            cli8:
            cli9:
        mds:
          hosts:
            mds0:
            mds1:
            mds2:
            mds3:
"""


def write_config(
    transport: str,
    striped: bool,
    ppn: int,
    client_mds_assignment: str,
    stripe_size: int = 1048576,
) -> None:
    assignment_suffix = (
        "" if client_mds_assignment == "first" else f"_mds-{client_mds_assignment}"
    )
    stripe_size_suffix = "" if stripe_size == 1048576 else f"_stripe-size-{stripe_size}"
    name = (
        f"transport-{transport}_striping-{'on' if striped else 'off'}"
        f"_ppn-{ppn}{assignment_suffix}{stripe_size_suffix}.yaml"
    )
    stripe_width = '"{{ groups[\'ds\'] | length }}"' if striped else "1"
    (OUTPUT_DIR / name).write_text(
        CONFIG.format(
            transport=transport,
            client_mds_assignment=client_mds_assignment,
            stripe_width=stripe_width,
            stripe_size=stripe_size,
            ppn=ppn,
        )
    )


def main() -> None:
    OUTPUT_DIR.mkdir(exist_ok=True)
    for transport, striped in VARIANTS:
        for ppn in PPNS:
            write_config(transport, striped, ppn, "first")

    write_config("rdma", True, 16, "round-robin")
    write_config("rdma", False, 16, "round-robin")
    for stripe_size in STRIPE_SIZE_SCREENING_BYTES:
        write_config("rdma", True, 16, "round-robin", stripe_size=stripe_size)


if __name__ == "__main__":
    main()
