#!/usr/bin/env python3
"""Generate the short-stonewall IO500 pNFS scaling configurations."""

from pathlib import Path


OUTPUT_DIR = Path(__file__).with_name("pnfs_io500_scaling")
TOPOLOGIES = (
    (1, 1, 1),
    (1, 1, 2),
    (1, 2, 1),
    (1, 2, 2),
    (2, 2, 2),
    (2, 4, 4),
    (4, 1, 10),
    (4, 2, 10),
    (4, 4, 10),
    (4, 8, 8),
    (4, 8, 10),
    (4, 10, 1),
    (4, 10, 2),
    (4, 10, 4),
    (4, 10, 8),
    (4, 10, 10),
)

CONFIG = """\
# Generated by configs/xem/generate_pnfs_io500_scaling.py.
all:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    current_user: "{{{{ lookup('env', 'USER') }}}}"
    host_domain: "{{{{ current_user }}}}.mvpnet"
    result_dir: '/proj/mvpnet/{{{{ current_user }}}}/experiments'
    local_storage: /mnt/local
    network:
      type: 'none'
    output_dir: "/tmp/{{{{ current_user }}}}/experiments"
    playbooks:
      bootstrap_cluster: "./playbooks/shared/prereqs.yaml"
      gold_install: "./playbooks/pnfs/install_golds/install_pnfs_all.yaml"
      cluster_config: "./playbooks/pnfs/configure_cluster/configure_pnfs_monolithic.yaml"
      cluster_test: "./playbooks/shared/io500_tester.yaml"
    system:
      type: 'pnfs'
      version: 'xx'
      pnfs_src: '/proj/mvpnet/jbent/pnfs-lattice/'
      rondb_url: 'https://repo.hops.works/master/rondb-26.02.4-linux-glibc2.28-x86_64.tar.gz'
      ds_transport: 'rdma'
      client_mds_assignment: 'first'
      stripe_width: 1
      stripe_size: 1048576
      hpc_serve_layouts: true
    io500:
      stonewall_time: 30
      ppn: 16
      result_metadata:
        mdsassign: "{{{{ system.client_mds_assignment }}}}"
      data_directory_xattrs:
        - name: user.pnfs.hpc_shared
          value: "{{{{ '1' if system.stripe_width | int > 1 else '0' }}}}"
    UNIQUE_TAG: "pmanual"

  children:
    physical_hosts:
      vars:
        ansible_host: "{{{{ inventory_hostname }}}}.{{{{ host_domain }}}}"
      children:
        ds:
          hosts:
{ds_hosts}
        clients:
          hosts:
{client_hosts}
        mds:
          hosts:
{mds_hosts}
"""


def hosts(prefix: str, count: int) -> str:
    return "\n".join(f"            {prefix}{index}:" for index in range(count))


def main() -> None:
    OUTPUT_DIR.mkdir(exist_ok=True)
    for mds_count, ds_count, client_count in TOPOLOGIES:
        name = f"mds-{mds_count}_ds-{ds_count}_clients-{client_count}.yaml"
        (OUTPUT_DIR / name).write_text(
            CONFIG.format(
                ds_hosts=hosts("ds", ds_count),
                client_hosts=hosts("cli", client_count),
                mds_hosts=hosts("mds", mds_count),
            )
        )


if __name__ == "__main__":
    main()
