# -------------------------------------------
#  Cleanup block
# -------------------------------------------
- name: Cleanup old TASSI networking for {{ UNIQUE_TAG }} 
  block:
    - name: Gather libvirt network facts
      community.libvirt.virt_net:
        command: facts
      register: libvirt_facts
    - name: Remove VM mappings from /etc/hosts
      blockinfile:
        path: /etc/hosts
        state: absent
        marker: "{{ etchosts_mark }}"
    - name: Remove routes from interfaces
      include_tasks: remove_interface.yaml
      loop:
        - "{{ libvirt.interface }}"
        - "{{ libvirt.name }}"
      loop_control:
        loop_var: iface
    - name: Destroy and undefine libvirt network if it exists
      block:
        - name: Destroy libvirt network if active
          command: "virsh net-destroy {{ libvirt.name }}"
          when: libvirt_facts.ansible_facts.ansible_libvirt_networks[libvirt.name] is defined and libvirt_facts.ansible_facts.ansible_libvirt_networks[libvirt.name].state == 'active'
        - name: Undefine libvirt network if it exists
          command: "virsh net-undefine {{ libvirt.name }}"
      when: libvirt.name in libvirt_facts.ansible_facts.ansible_libvirt_networks
  tags: makeclean

# -------------------------------------------
#  Create libvirt bridge and network
# -------------------------------------------
- name: Configure TASSI networking for {{ UNIQUE_TAG }}
  block:
  - name: Debug bridge setup variables
    ansible.builtin.debug:
      msg:
        - "libvirt.interface: {{ libvirt.interface }}"
        - "network.interface: {{ libvirt.name }}"
        - "network_base_ip: {{ libvirt.base_ip }}"
        - "bridge_ip: {{ bridge_ip }}"

  - name: Create bridge interface for libvirt
    community.general.nmcli:
      conn_name: "{{ libvirt.interface }}"
      ifname: "{{ libvirt.interface }}"
      type: bridge
      state: present
      autoconnect: yes
      ip4: "{{ bridge_ip }}" 
    register: bridge_creation

  - name: Attach physical interface to bridge
    community.general.nmcli:
      conn_name: "{{ network.interface }}"
      ifname: "{{ network.interface }}"
      type: ethernet
      master: "{{ libvirt.interface }}"
      slave_type: bridge
      state: present
      autoconnect: yes

  - name: Bring up slave interface
    ansible.builtin.command: "nmcli connection up {{ network.interface }}"

  - name: Bring up the bridge interface
    ansible.builtin.command: "ip link set {{ libvirt.interface }} up"

  - name: Wait for bridge to get carrier
    ansible.builtin.command: "cat /sys/class/net/{{ libvirt.interface }}/carrier"
    register: bridge_carrier
    changed_when: false
    until: bridge_carrier.stdout == "1"
    retries: 20
    delay: 7
    failed_when: bridge_carrier.stdout != "1"

  - name: Print bridge carrier status
    ansible.builtin.debug:
      msg: "Bridge {{ libvirt.interface }} carrier: {{ bridge_carrier.stdout }}"

  - name: Add route to {{ libvirt.base_ip }}.0/{{ libvirt.cidr }} via {{ libvirt.interface }}
    ansible.builtin.command:
      argv:
        - ip
        - route
        - add
        - "{{ libvirt.base_ip }}.0/{{ libvirt.cidr }}"
        - dev
        - "{{ libvirt.interface }}"

  - name: Create libvirt network definition
    copy:
      dest: "{{ libvirt_network_xml }}"
      content: |
        <network>
          <name>{{ libvirt.name }}</name>
          <forward mode='bridge'/>
          <bridge name='{{ libvirt.interface }}'/>
        </network>

  # comment to fix vim autocoloring '

  - name: Define libvirt network {{ libvirt.name }} using {{ libvirt_network_xml }}
    command: "virsh net-define {{ libvirt_network_xml }}"

  - name: Start and autostart libvirt network
    block:
      - name:
        command: "virsh net-start {{ libvirt.name }}"
        register: net_start
        changed_when: "'is already active' not in net_start.stderr"
      - name: Enable autostart
        command: "virsh net-autostart {{ libvirt.name }}"
        register: net_autostart
        changed_when: "'marked as autostart' in net_autostart.stdout"

  - name: Configure Routing and NAT
    include_tasks: configure_nat_routing.yaml
    vars:
      # Pass the Physical Secondary NIC as the backend
      backend_interface: "{{ network.interface }}"

  - name: Add VMs to /etc/hosts for debugging
    blockinfile:
      path: /etc/hosts
      marker: "{{ etchosts_mark }}"
      block: |
        {% for vm in groups['vms'] %}
        {{ hostvars[vm]['ansible_host'] }}  {{ vm }}
        {% endfor %}
  when: "'makeclean' not in ansible_run_tags"
