- name: Check for Network Type and Handle Appropriately 
  hosts: physical_hosts 
  any_errors_fatal: yes
  become: false
  gather_facts: false
  vars:
    etchosts_mark: "# {mark} TASSI {{ UNIQUE_TAG }} VMs - managed by Ansible"
    libvirt_network_xml: "/etc/libvirt/qemu/networks/{{ libvirt.name }}.xml"
    ansible_remote_tmp: /tmp

  tasks:
    - name: Network Configuration
      block:
      - name: Fail if network.type is not defined
        fail:
          msg: "'network.type' must be defined"
        when: network.type is not defined

      - name: Fail if network.type is unsupported
        fail:
          msg: "'network.type' must be either 'private' or 'wireguard' or 'mvpnet'. Got: {{ network.type }}"
        when: network.type is defined and network.type not in ['private', 'wireguard', 'mvpnet']

      - name: Include tasks for private or wireguard tasks if needed
        become: true
        block:
        - name: Validate and include private network playbook
          when: network.type == 'private'
          block:
            - name: Assert 'network.interface' is defined
              assert:
                that: network.interface is defined
                fail_msg: "'network.interface' must be defined for private networks"
            - name: Include private network setup playbook
              include_tasks: create_private_network.yaml

        - name: Validate and include wireguard network playbook
          when: network.type == 'wireguard'
          block:
            - name: Assert 'wg_base_ip' and 'wg_cidr' are defined
              assert:
                that:
                  - network.wg_base_ip is defined
                  - network.wg_cidr is defined
                fail_msg: "'network.wg_base_ip' and 'network.wg_cidr' must be defined for wireguard networks"
            - name: Include wireguard tunnel setup playbook
              include_tasks: create_wireguard_tunnels.yaml
      tags: always 
