- name: Set IOR Config options 
  set_fact:
    ior_config_option: '' # no config options for beegfs install 

- name: Ensure marker directory exists 
  include_tasks: ../../shared/ensure_marker_dir.yaml

- include_tasks: install_beegfs7.yaml
  when: system.version is match('^7')

- include_tasks: install_beegfs8.yaml
  when: system.version is match('^8')

- include_tasks: ../../shared/install_tools.yaml

- include_tasks: ../../shared/disable_firewall_selinux.yaml
