- name: Set IOR Config options 
  set_fact:
    ior_config_option: '' # no config options for beegfs install 

- name: Ensure marker directory exists 
  include_tasks: ../../shared/ensure_marker_dir.yaml

- include_tasks: install_beegfs.yaml

- include_tasks: ../../shared/install_tools.yaml

- include_tasks: ../../shared/disable_firewall_selinux.yaml
