- hosts: localhost
  gather_facts: false
  tasks:
    - name: Define and ensure relevant directories 
      block:
      - name: Define an artifact directory
        set_fact: 
          artifact_dir: "../../artifacts/{{ UNIQUE_TAG }}"
          inventory_dir: "../../artifacts/{{ UNIQUE_TAG }}/inventory"
          qcow2_dir: "{{ image_storage.qcow }}/{{ UNIQUE_TAG }}"

      - name: Ensure necessary directories exist
        file:
          path: "{{ item }}"
          state: directory
          mode: '0755'
        loop:
          - "{{ artifact_dir }}"
          - "{{ inventory_dir }}"
          - "{{ qcow2_dir }}"

    - name: Define necessary variables
      block:
      - name: Define qcow2 paths for each role
        set_fact:
          gold_qcow2_paths: >-
            {{
              dict(vm_roles.values() | zip(vm_roles.values() | map('regex_replace', '^', qcow2_dir ~ '/') | map('regex_replace', '$', '.qcow2')))
              | dict2items | items2dict
            }}

      - name: Debug qcow2 paths 
        block:
          - debug:
              msg: "VM: {{ item.0 }}, Role: {{ item.1 }}, Resolved Path: {{ gold_qcow2_paths.get(item.1, 'MISSING_PATH') }}"
            loop: "{{ groups['all'] | map('extract', hostvars, 'vms') | select('defined') | list | flatten(1) }}"
          
          - debug:
              var: gold_qcow2_paths

      - name: Compute final_gold_vms dictionary with recursive merging of default gold with individual
        set_fact:
          final_gold_vms: "{{ computed_final_gold_vms }}"
        vars:
          computed_final_gold_vms: >-
            {%- set result = {} -%}
            {%- for vm in (gold_vms.individual | default([])) -%}
              {%- set merged_vm = gold_vms.defaults | combine(vm, recursive=True) -%}
              {%- set _ = result.update({merged_vm.group: merged_vm}) -%}
            {%- endfor -%}
            {%- if (gold_vms.individual | default([])) | length == 0 -%}
              {%- set _ = result.update({gold_vms.defaults.group: gold_vms.defaults}) -%}
            {%- endif -%}
            {{ result }}


      - name: Debug final_gold_vms structure
        debug:
          var: final_gold_vms

      - name: Set common network interface variables
        set_fact:
          wireguard:
            interface: "wg-{{ UNIQUE_TAG }}"
            cidr: "{{ network.wireguard.cidr }}"
          libvirt:
            interface: "wgbr-{{ UNIQUE_TAG }}"
            name: "vmwgbr-{{ UNIQUE_TAG }}"

      - name: Define a ton of derived stuff for each VM to make later templating easier 
        set_fact:
          vm_info: "{{ computed_vm_info }}"
        vars:
          network_data: "{{ hostvars['localhost'].network }}"  # Explicitly fetch network
          computed_vm_info: >
            {%- set ns = namespace(mac_counter=0, result=[]) -%}
            {%- for phys in groups['all'] if hostvars[phys].vms is defined -%}
              {%- for vm in hostvars[phys].vms -%}
                {%- set mac = "52:54:00:" ~ ("%02x" | format(ns.mac_counter //(256*256))) ~ ":" ~ ("%02x" | format((ns.mac_counter // 256) % 256)) ~ ":" ~ ("%02x" | format(ns.mac_counter % 256)) -%}
                {%- set _ = ns.result.append({
                      'name': vm[0],
                      'ansible_host': hostvars[phys].network.libvirt.base_ip ~ '.' ~ vm[4],
                      'group': vm[1],
                      'hdd1_size': vm[2],
                      'hdd2_size': vm[3],
                      'libvirt_bridge': network.libvirt.base_ip ~ '.' ~ (hostvars[phys].libvirt_suffix | int + 1),
                      'mac_address': mac,
                      'machine': final_gold_vms.get(vm[1]).machine, 
                      'memory': final_gold_vms.get(vm[1]).memory, 
                      'netone': network.libvirt.default, 
                      'nettwo': libvirt.name, 
                      'physical_host': phys,
                      'source_image': gold_qcow2_paths.get(vm[1]), 
                      'storage_pool': final_gold_vms.get(vm[1]).storage_pool, 
                      'vcpu': final_gold_vms.get(vm[1]).vcpu, 
                    }) -%}
                {%- set ns.mac_counter = ns.mac_counter + 1 -%}
              {%- endfor -%}
            {%- endfor -%}
            {{ ns.result }}

      - name: Debug VM info structure
        debug:
          var: vm_info

      - name: Capture variables for the template provenance headers 
        set_fact:
          playbook_command: "{{ lookup('file', '/proc/self/cmdline') | regex_replace('\u0000', ' ') }}"
          current_date: "{{ lookup('pipe', 'date \"+%Y-%m-%d %H:%M:%S\"') }}"
          ansible_hostname: "{{ lookup('pipe', 'hostname') }}"

    - name: Generate inventory and var files for subsequent phases
      block:
      - block:
        - name: Generate shared inventory file
          template:
            src: templates/all_inventory.j2
            dest: "{{ inventory_dir }}/all.yaml"

        - name: Generate phase 1 inventory file (gold VMs) 
          template:
            src: templates/phase1_gold_inventory.j2
            dest: "{{ inventory_dir }}/phase1_make_gold.yaml"

        - name: Generate phase 2 inventory file (networking) 
          template:
            src: templates/phase2_networking.j2 
            dest: "{{ inventory_dir }}/phase2_networking.yaml"
        vars:
          comment_style: "hash"

      - name: Generate phase 3 opentofu vars file
        template:
          src: templates/phase3_vms.j2
          dest: "{{ artifact_dir }}/phase3_vms.tfvars"
        register: phase3_tfvars_result
        vars:
          comment_style: "hcl"

      - name: Format the autogenerated opentofu file 
        ansible.builtin.command:
          cmd: tofu fmt "{{ phase3_tfvars_result.dest }}" 

    - debug:
        msg: "Necessary artifacts for TASSI {{ UNIQUE_TAG }} are now available at {{ artifact_dir }}. Proceed with remaining TASSI phases accordingly."

