- hosts: localhost
  gather_facts: true
  tasks:
    - name: Define and ensure relevant directories 
      block:
      - name: Define an artifact directory
        set_fact: 
          artifact_dir: "../../artifacts/{{ UNIQUE_TAG }}/inventory"

      - name: Define a qcow2 directory
        set_fact:
          qcow2_dir: "{{ image_storage.qcow }}/{{ UNIQUE_TAG }}"

      - name: Ensure necessary directories exist
        file:
          path: "{{ item }}"
          state: directory
          mode: '0755'
        loop:
          - "{{ artifact_dir }}"
          - "{{ qcow2_dir }}"

    - name: Define necessary variables
      block:
      - name: Define qcow2 paths for each role
        set_fact:
          gold_qcow2_paths: >-
            {{
              dict(vm_roles.values() | zip(vm_roles.values() | map('regex_replace', '^', qcow2_dir ~ '/') | map('regex_replace', '$', '.qcow2')))
              | dict2items | items2dict
            }}

      - name: Debug qcow2 paths 
        debug:
          var: gold_qcow2_paths

      - name: Debug each VM role lookup
        debug:
          msg: "VM: {{ item.0 }}, Role: {{ item.1 }}, Resolved Path: {{ gold_qcow2_paths.get(item.1, 'MISSING_PATH') }}"
        loop: "{{ groups['all'] | map('extract', hostvars, 'vms') | select('defined') | list | flatten(1) }}"


      - name: Define a ton of derived stuff for each VM to make later templates easier 
        set_fact:
          vm_info: "{{ computed_vm_info }}"
        vars:
          computed_vm_info: >
            {%- set ns = namespace(mac_counter=0, result=[]) -%}
            {%- for phys in groups['all'] if hostvars[phys].vms is defined -%}
              {%- for vm in hostvars[phys].vms -%}
                {%- set mac = "52:54:00:" ~ ("%02x" | format(ns.mac_counter //(256*256))) ~ ":" ~ ("%02x" | format((ns.mac_counter // 256) % 256)) ~ ":" ~ ("%02x" | format(ns.mac_counter % 256)) -%}
                {%- set libvirt_suffix_plus_one = hostvars[phys].libvirt_suffix | int + 1 -%}
                {%- set source_img = gold_qcow2_paths.get(vm[1], 'MISSING_PATH') -%}
                {%- set _ = ns.result.append({
                      'name': vm[0],
                      'physical_host': phys,
                      'ansible_host': hostvars[phys].network.libvirt.base_ip ~ '.' ~ vm[4],
                      'group': vm[1],
                      'hdd1_size': vm[2],
                      'hdd2_size': vm[3],
                      'mac_address': mac,
                      'source_image': source_img, 
                      'libvirt_bridge': network.libvirt.base_ip ~ '.' ~ libvirt_suffix_plus_one,
                    }) -%}
                {%- set ns.mac_counter = ns.mac_counter + 1 -%}
              {%- endfor -%}
            {%- endfor -%}
            {{ ns.result }}

      - name: Debug VM info structure
        debug:
          var: vm_info

      - name: Set common network interface variables
        set_fact:
          wireguard:
            interface: "wg-{{ UNIQUE_TAG }}"
            cidr: "{{ network.wireguard.cidr }}"
          libvirt:
            interface: "wgbr-{{ UNIQUE_TAG }}"
            name: "vmwgbr-{{ UNIQUE_TAG }}"

      - name: Capture playbook command line for the autogenerated opentofu file 
        set_fact:
          playbook_command: "{{ lookup('file', '/proc/self/cmdline') | regex_replace('\u0000', ' ') }}"
      

    - name: Generate inventory and var files for subsequent phases
      block:
      - name: Generate shared inventory file
        template:
          src: templates/all_inventory.j2
          dest: "{{ artifact_dir }}/all.yaml"

      - name: Generate phase 1 inventory file (gold VMs) 
        template:
          src: templates/phase1_gold_inventory.j2
          dest: "{{ artifact_dir }}/phase1_make_gold.yaml"

      - name: Generate phase 2 inventory file (networking) 
        template:
          src: templates/phase2_networking.j2 
          dest: "{{ artifact_dir }}/phase2_networking.yaml"

      - name: Generate phase 3 opentofu vars file
        template:
          src: templates/phase3_vms.j2
          dest: "{{ artifact_dir }}/phase3_vms.tfvars"
        register: phase3_tfvars_result

      - name: Format the autogenerated opentofu file 
        ansible.builtin.command:
          cmd: tofu fmt "{{ phase3_tfvars_result.dest }}" 

