- hosts: localhost
  gather_facts: false
  tasks:
    - name: Define an artifact directory
      set_fact: 
        artifact_dir: "../../artifacts/{{ UNIQUE_TAG }}/inventory"

    - name: Define a qcow2 directory
      set_fact:
        qcow2_dir: "{{ image_storage.qcow }}/{{ UNIQUE_TAG }}"

    - name: Ensure necessary directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ artifact_dir }}"
        - "{{ qcow2_dir }}"

    - name: Generate shared inventory file
      template:
        src: templates/shared_inventory.j2
        dest: "{{ artifact_dir }}/all.yaml"

    - name: Generate phase 1 inventory file (making gold VMs) 
      template:
        src: templates/phase1_gold_inventory.j2
        dest: "{{ artifact_dir }}/phase1_make_gold.yaml"
