- name: Delete old bridge connection {{ iface }}
  community.general.nmcli:
    conn_name: "{{ iface }}"
    state: absent
  ignore_errors: yes

- name: Get current routes for interface {{ iface }}
  ansible.builtin.command: ip route show dev {{ iface }}
  register: route_output
  changed_when: false
  failed_when: route_output.rc != 0 and 'Cannot find device' not in route_output.stderr

- name: Remove all routes on {{ iface }}
  ansible.builtin.command:
    cmd: "ip route del {{ item }}"
  loop: "{{ route_output.stdout_lines }}"
  when: item is match('^\\d')  # skip non-IP lines just in case

