---
- name: Configure BeeGFS on all nodes
  hosts: all
  gather_facts: no

- import_playbook: ../../shared/configure_ssh.yaml
  tags:
    - setup

- import_playbook: configure_variables.yaml

- import_playbook: configure_beegfs_servers.yaml

- import_playbook: configure_beegfs_clients.yaml

- import_playbook: ../../shared/sanity_test.yaml
  vars: { sanity_debug_msg: "After configuring beegfs" }
