---
- name: Configure BeeGFS on clients
  hosts: all
  become: yes
  tasks:
    - block:
      - name: Setup BeeGFS client
        ansible.builtin.command:
          cmd: "{{ setup_command }}"

      - name: Start beegfs-helperd
        ansible.builtin.systemd:
          name: beegfs-helperd
          state: started
          enabled: yes

      - name: Start beegfs-client
        ansible.builtin.systemd:
          name: beegfs-client
          state: started
          enabled: yes
      when: "'clients' in group_names"

    - name: Get the first client node
      set_fact:
        first_client_node: "{{ groups['clients'] | first }}"

    # do a bunch of debugging stuff
    - block:
      - name: List BeeGFS nodes with NIC details
        ansible.builtin.command:
          cmd: "beegfs-ctl --listnodes --nodetype={{ item }} --nicdetails"
        with_items:
          - meta
          - storage
          - client

      - name: Check BeeGFS network
        ansible.builtin.command:
          cmd: beegfs-net

      - name: Check BeeGFS servers
        ansible.builtin.command:
          cmd: beegfs-check-servers

      - name: Check BeeGFS disk space
        ansible.builtin.command:
          cmd: beegfs-df
      when: inventory_hostname == first_client_node

