---
- name: Configure BeeGFS on all nodes
  hosts: all
  gather_facts: no # don't do this before we wait on ssh
  strategy: linear # must be linear because servers must finish configuring before clients can start
  vars:
    connauthfile: /etc/beegfs/connauthfile
    loglevel: 5
    conninterfacefile: /etc/beegfs/beegfs-conn-interfaces

  tasks:
    - block:
      - name: Include wait_ssh task
        include_tasks: ../../shared/wait_ssh.yaml

      - name: Configure ssh
        include_tasks: ../../shared/configure_ssh.yaml
      tags: setup

    - name: Gather only the network facts
      setup:
        gather_subset:
          - network

    - name: Ensure marker directory exists
      include_tasks: ../../shared/ensure_marker_dir.yaml

    - include_tasks: configure_variables.yaml

    - include_tasks: configure_beegfs_networking.yaml

    - include_tasks: configure_beegfs_servers.yaml

    - name: Pause for 120 seconds to let BeegFS servers start
      ansible.builtin.pause:
        seconds: 120

    - include_tasks: configure_beegfs_clients.yaml
