---
- name: Configure BeeGFS on all nodes
  hosts: all
  gather_facts: no
  strategy: linear # must be linear because servers must finish configuring before clients can start
  vars:
    connauthfile: /etc/beegfs/connauthfile
    loglevel: 5
    conninterfacefile: /etc/beegfs/beegfs-conn-interfaces

  tasks:
    - block:
      - name: Include wait_ssh task
        include_tasks: ../../shared/wait_ssh.yaml

      - name: Configure ssh
        include_tasks: ../../shared/configure_ssh.yaml
      tags: setup

    - include_tasks: configure_variables.yaml

    - include_tasks: configure_beegfs_networking.yaml

    - include_tasks: configure_beegfs_servers.yaml

    - include_tasks: configure_beegfs_clients.yaml
