# this inventory describes a lustre cluster following these instructions: 
# https://gitlab.newmexicoconsortium.org/jbent/tassi/-/blob/main/doc/lustre_install/lustre_vm.pdf
# additionally, the node on which this is run might need to be set up correctly:
# https://gitlab.newmexicoconsortium.org/jbent/tassi/-/blob/main/doc/lustre_install/john_notes.txt
all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
    ansible_playbooks:
        install: './ansible/install_empty.yaml'
        config: './ansible/configure_empty.yaml'
        test: './ansible/test_empty.yaml'
    test_script: 
        path: './tests/test_pdsh.sh'
        args: 'client00,client01,meta00,meta01,data00,data01' 
    vm_dir: '/mnt/usrc-storage-nfs/jbent/images' 
    bootstrap_vm:
      cpus: 2
      boot_hdd_gbs: 12
      memory_mbs: 4096
      root_pwd: password
      location: '/mnt/usrc-storage-nfs/jbent/images/alma/AlmaLinux-8.10-x86_64-minimal.iso'
      os_variant: 'almalinux8'
      auth_keys: '/home/jbent/.ssh/authorized_keys'
    network: 
      addr: '192.168.56'
    system:
      type: 'empty'
  children:
    clients:
      vars:
        hds: []
      hosts:
        client00:
          ip: 50
        client01:
          ip: 60
    servers:
      vars:
      children:
        meta:
          vars:
            hds: [5]
          hosts:
            meta00:
              ip: 10
            meta01:
              ip: 20
        data:
          vars: 
            hds: [10]
          hosts:
            data00:
              ip: 30
            data01:
              ip: 40
