# this inventory describes a lustre cluster following these instructions: 
# https://gitlab.newmexicoconsortium.org/jbent/tassi/-/blob/main/doc/lustre_install/lustre_vm.pdf
# additionally, the node on which this is run might need to be set up correctly:
# https://gitlab.newmexicoconsortium.org/jbent/tassi/-/blob/main/doc/lustre_install/john_notes.txt
all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
    ansible_playbook_install: './ansible/install_all.yaml'
    ansible_playbook_config: './ansible/configure_all.yaml'
    ansible_playbook_test: './ansible/test_lustre.yaml'
    test_script: './tests/simple_mpi_ior.sh'
    vm_dir: '/mnt/usrc-storage-nfs/jbent/images'
    bootstrap_vm:
      cpus: 2
      boot_hdd_gbs: 12
      memory_mbs: 4096
      root_pwd: password
      location: 'http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/'
      auth_keys: '/home/jbent/.ssh/authorized_keys'
    network: 
      addr: '192.168.56'
    lustre:
      mgs_node: '192.168.56.10@tcp:192.168.56.20@tcp'
      version: '2.15.4-RC2' 
      backfstype: 'zfs'
      patch: '/mnt/usrc-storage-nfs/jbent/patches/lustre/test_patch.patch' 
    zfs:
      version: zfs-2.1.11 
      patch: '/mnt/usrc-storage-nfs/jbent/patches/zfs/zfs_patch1.patch' 
  children:
    clients:
      vars:
        configure_args: '--disable-server --enable-client'
      hosts:
        client00:
          ip: 50
          target_mount: '/mnt/lustre'
          hds: []
        client01:
          ip: 60
          target_mount: '/mnt/lustre'
          hds: []
    servers:
      vars:
        configure_args: '--with-zfs --disable-ldiskfs --enable-server'
      children:
        mds:
          vars:
            target_type: mdt
          hosts:
            mds00:
              ip: 10
              failnode: 20
              index: 0
              mgt_mount: '/mnt/lustre/mgt'
              mgt_target: 'lustre-mgs' 
              target: 'lustre-mds00/mdt0'
              target_mount: '/mnt/lustre/mds00.mdt0'
              hds: [5, 5]
            mds01:
              ip: 20
              failnode: 10
              index: 1
              target: 'lustre-mds01/mdt0'
              target_mount: '/mnt/lustre/mds01.mdt0'
              hds: [5]
        oss:
          vars: 
            target_type: ost
            hds: [10]
          hosts:
            oss00:
              ip: 30
              failnode: 40
              index: 0
              target: 'lustre-oss00/ost0'
              target_mount: '/mnt/lustre/oss00.ost0'
            oss01:
              ip: 40
              failnode: 30
              index: 1
              target: 'lustre-oss01/ost0'
              target_mount: '/mnt/lustre/oss01.ost0'
