---
- import_playbook: configure_ssh.yaml

- name: Configure an empty system. Nothing to do.
  hosts: all
  gather_facts: false # needed for {{ ansible_architecture }}, do it later so we can wait for ssh
  any_errors_fatal: true

  tasks:
    - name: Wait for SSH to become ready
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        timeout: 300
      delegate_to: localhost
      become: false

    - name: Gather facts
      setup:

    - name: Check firewall status
      ansible.builtin.service:
        name: firewalld
        state: stopped
      register: firewall_status
      failed_when: firewall_status.state == "running"
      tags:
        - lustre
        - config
        - precheck

    - name: Check SELinux status
      command: getenforce
      register: selinux_status
      changed_when: false
      tags:
        - selinux
        - lustre
        - config
        - precheck

    - name: Verify SELinux is disabled
      assert:
        that:
          - selinux_status.stdout == "Disabled"
        fail_msg: "Error: SELinux is not disabled. Current status is {{ selinux_status.stdout }}"
      no_log: yes
      tags:
        - selinux
        - lustre
        - config
        - precheck

    - name: Ping other nodes to ensure hostonly network is working
      command: "ping -c 3 {{ hostvars[item].network.addr }}.{{ hostvars[item].ip }}"
      with_items: "{{ groups['all'] }}"
      when: "inventory_hostname != item"
      ignore_errors: true
      register: ping_result
