---
- name: Configure a Lustre Cluster 
  hosts: all
  gather_facts: true # needed for {{ ansible_architecture }}
  any_errors_fatal: true
  vars_files:
    - ./lustre_vars.yaml

  tasks:
    - name: Disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      tags: 
        - firewalld
        - lustre
        - config

    - name: Check status of firewalld
      systemd:
        name: firewalld
        state: started
      register: firewalld_status
      ignore_errors: yes
      tags: 
        - firewalld
        - lustre
        - config

    - name: Print firewalld status
      debug:
        msg: "Firewalld is currently {{ 'enabled' if firewalld_status.status.ActiveState == 'active' else 'disabled' }}"
      tags: 
        - firewalld
        - lustre
        - config


    - name: Disable SELinux
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*$'
        replace: 'SELINUX=disabled'
      register: selinux_config
      tags: 
        - selinux
        - lustre
        - config


    - name: Check SELinux status
      command: sestatus
      register: sestatus_output
      tags: 
        - selinux
        - lustre
        - config

    - name: Print SELinux status
      debug:
        msg: "SELinux is currently {{ 'enabled' if 'enforcing' in sestatus_output.stdout else 'disabled' }}"
      tags: 
        - selinux
        - lustre
        - config
