---
- name: Configure BeeGFS
  hosts: all
  become: yes
  tasks:
    - name: Ensure BeeGFS directories exist
      ansible.builtin.file:
        path: "{{ target_directory }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: "'meta00' in inventory_hostname or 'meta01' in inventory_hostname or 'data' in group_names"

    - name: Configure BeeGFS services
      ansible.builtin.command:
        cmd: "{{ setup_command }}"
      when: "'meta00' in inventory_hostname or 'meta01' in inventory_hostname or 'data' in group_names"

    - name: Enable and start BeeGFS services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - beegfs-mgmtd
        - beegfs-meta
        - beegfs-storage
      when: >
        (inventory_hostname == 'meta00' and item == 'beegfs-mgmtd') or
        (inventory_hostname == 'meta01' and item == 'beegfs-meta') or
        ('data' in group_names and item == 'beegfs-storage')
