---
- name: Configure a Lustre Cluster 
  hosts: all
  gather_facts: true # needed for {{ ansible_architecture }}
  any_errors_fatal: true

  tasks:
    - name: Check firewall status
      ansible.builtin.service:
        name: firewalld
        state: stopped
      register: firewall_status
      failed_when: firewall_status.state == "running"

    - name: Check SELinux status
      command: getenforce
      register: selinux_status
      changed_when: false
      tags:
        - selinux
        - lustre
        - config

    - name: Verify SELinux is disabled
      assert:
        that:
          - selinux_status.stdout == "Disabled"
        fail_msg: "Error: SELinux is not disabled. Current status is {{ selinux_status.stdout }}"
      no_log: yes
      tags:
        - selinux
        - lustre
        - config

    - name: Verify {{ module_name }} module is loaded
      command: lsmod
      register: lsmod_output
      failed_when: "module_name not in lsmod_output.stdout"
      no_log: no
      loop:
        - lustre
        - zfs
      loop_control:
        loop_var: module_name
      tags:
        - modules
        - lustre
        - config
      when: "'servers' in group_names"

    - name: Unmount client mounts 
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      with_items: "{{ target_mount }}"
      when: 
        - target_mount is defined
        - "'clients' in group_names"

    - name: Unmount OSS and MDS mounts 
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      with_items: "{{ target_mount }}"
      when: 
        - target_mount is defined
        - "'servers' in group_names"

    - name: Unmount MGS mount 
      ansible.builtin.mount:
        path: "{{ item }}"
        state: unmounted
      with_items: "{{ mgt_mount }}"
      when: mgt_mount is defined

    - name: Stop Lustre service
      ansible.builtin.systemd:
        name: lustre
        state: stopped
      when: "'servers' in group_names"

    - name: Stop LNet service
      ansible.builtin.systemd:
        name: lnet
        state: stopped
      when: "'servers' in group_names"

    # would be nice if this one didn't destroy all but just destroyed the ones created later
    - name: Destroy all ZFS pools
      ansible.builtin.shell: |
        for pool in $(zpool list -H -o name); do
          zpool destroy $pool
        done
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Remove mgs mount points if they exist
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ mgt_mount }}"
      when: mgt_mount is defined

    - name: Remove mds and oss and client mount points if they exist
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ target_mount }}"
      when: target_mount is defined

    - name: Find the full path of the ost and mdt devices
      ansible.builtin.shell: "ls /dev/disk/by-id/*_sdb"
      register: device_path
      changed_when: false
      when: "'servers' in group_names"

    - name: Create ZFS pools for osts and mdts
      ansible.builtin.command: 
        cmd: "zpool create lustre-{{ ansible_hostname }} {{ device_path.stdout }}"
      args:
        creates: "/dev/zvol/lustre-{{ ansible_hostname }}"
      when: 
        - "'servers' in group_names"
        - device_path.stdout != ""

    - name: Find the full path of the mgs device 
      ansible.builtin.shell: "ls /dev/disk/by-id/*_sdc"
      register: mgs_device_path
      changed_when: false
      when: mgt_target is defined

    - name: Create ZFS pool for mgt 
      ansible.builtin.command: 
        cmd: "zpool create {{ mgt_target }} {{ mgs_device_path.stdout }}"
      args:
        creates: "/dev/zvol/{{ mgt_target }}"
      when: 
        - mgt_target is defined

    - name: Generate host ID for all hosts
      ansible.builtin.command: genhostid
      register: genhostid_result
      changed_when: "'Host ID set to' in genhostid_result.stdout"

    - name: Create Lustre filesystem on MGS
      ansible.builtin.command:
        cmd: "mkfs.lustre --mgs --backfstype={{ lustre.backfstype }} --fsname=lustre {{ mgt_target }}/mgt"
      when: mgt_target is defined

    - name: Create Lustre filesystems on MDSes and OSSes
      command: >
        mkfs.lustre --reformat
        --{{ target_type }}
        --mgsnode={{ lustre.mgs_node }}
        --failnode={{ network.addr }}.{{ failnode }}@tcp
        --backfstype={{ lustre.backfstype }}
        --fsname=lustre
        --index={{ index }}
        {{ target }}
      vars:
        target_type: "{{ hostvars[inventory_hostname].target_type }}"
        failnode: "{{ hostvars[inventory_hostname].failnode }}"
        index: "{{ hostvars[inventory_hostname].index }}"
        target: "{{ hostvars[inventory_hostname].target }}"
      when: 
        - "'servers' in group_names"
        - target is defined

    - name: Create MDS and OSS and client mount points
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ target_mount }}"
      when: target_mount is defined

    - name: Create MGS mount point
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ mgt_mount }}"
      when: mgt_mount is defined

    - name: Mount MGS target
      ansible.builtin.shell:
        cmd: "mount -t lustre {{ mgt_target }}/mgt {{ mgt_mount }}"
      when: mgt_target is defined and mgt_mount is defined

    - name: Mount MDS and OSS targets
      ansible.builtin.shell:
        cmd: "mount -t lustre {{ target }} {{ target_mount }}"
      when: target is defined and target_mount is defined

    - name: Mount client
      ansible.builtin.shell:
        cmd: "mount -t lustre {{ lustre.mgs_node }}:/lustre {{ target_mount }}"
      when: 
        - target_mount is defined 
        - "'clients' in group_names"
