---
- name: Configure BeeGFS on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Include set_hostname
      include_tasks: set_hostname.yaml

    - name: Gather facts
      setup:

- import_playbook: configure_beegfs_servers.yaml

- import_playbook: configure_beegfs_clients.yaml
