---
- name: Configure a Lustre Cluster 
  hosts: all
  gather_facts: true # needed for {{ ansible_architecture }}
  any_errors_fatal: true
  vars_files:
    - ./lustre_vars.yaml

  tasks:
    - name: Install ZFS RPMs
      shell: dnf localinstall *.rpm
      args:
        executable: /bin/bash
        chdir: "{{ zfs_rpms }}"
      when: "group_names | join(' ') | regex_search('lustre_servers')"
      tags: 
        - install
        - lustre
        - zfs
        - rpms

    - name: Download resource-agents RPM
      # this is an annoying playbook task. We shouldn't need this and I couldn't find this RPM in any of the RPM repos so have to one-off manually do it.
      ansible.builtin.get_url:
        url: https://yum.oracle.com/repo/OracleLinux/OL8/addons/x86_64/getPackage/resource-agents-4.9.0-29.el8.x86_64.rpm
        dest: /tmp/resource-agents-4.9.0-29.el8.x86_64.rpm
      tags: 
        - install
        - lustre
        - rpms

    - name: Import Oracle Linux GPG Key
      ansible.builtin.rpm_key:
        state: present
        key: https://yum.oracle.com/RPM-GPG-KEY-oracle-ol8
      tags: 
        - install
        - lustre
        - rpms

    - name: Install resource-agents RPM
      ansible.builtin.dnf:
        name: /tmp/resource-agents-4.9.0-29.el8.x86_64.rpm
        state: present
      tags: 
        - install
        - lustre
        - rpms

    - name: Install Lustre RPMs
      # seems to hang. Do it another way.
      shell: dnf localinstall *.rpm
      when: false
      args:
        executable: /bin/bash
        chdir: "{{ lustre_rpms }}"
      tags: 
        - install
        - lustre
        - zfs
        - rpms

    - name: Find Lustre RPM files 
      find:
        paths: "{{ lustre_rpms }}"
        patterns: "*.rpm"
      register: rpm_files
      tags: 
        - install
        - lustre
        - rpms

    - name: Install Lustre RPMs
      dnf:
        name: "{{ rpm_files.files | map(attribute='path') | list }}"
        state: present
        disable_gpg_check: yes
      tags: 
        - install
        - lustre
        - rpms

