---
- name: Configure Lustre on all nodes 
  hosts: all
  gather_facts: no
  tasks:
    - name: Include set_hostname
      include_tasks: set_hostname.yaml

    - name: Gather facts
      setup:

- name: Configure passwordless ssh 
  import_playbook: configure_ssh.yaml

- name: Configure Lustre
  import_playbook: configure_lustre.yaml
