---
- name: Configure an empty system. 
  hosts: all
  gather_facts: false # needed for {{ ansible_architecture }}, do it later so we can wait for ssh
  any_errors_fatal: true

  tasks:
    - name: Include wait_ssh task
      include_tasks: wait_ssh.yaml

    - name: Gather facts
      setup:

    - name: Include set_hostname 
      include_tasks: set_hostname.yaml

    # just move this to the install
    #- name: Include disable firewall and selinux
    #  include_tasks: disable_firewall_selinux.yaml

- import_playbook: configure_ssh.yaml

