---
- name: Configure BeeGFS on clients
  hosts: all
  become: yes
  tasks:
    - name: Setup BeeGFS client
      ansible.builtin.command:
        cmd: /opt/beegfs/sbin/beegfs-setup-client -m meta00
      when: "'clients' in group_names"

    - name: Start beegfs-helperd
      ansible.builtin.systemd:
        name: beegfs-helperd
        state: started
        enabled: yes
      when: "'clients' in group_names"

    - name: Start beegfs-client
      ansible.builtin.systemd:
        name: beegfs-client
        state: started
        enabled: yes
      when: "'clients' in group_names"

    - name: Get the first client node
      set_fact:
        first_client_node: "{{ groups['clients'] | first }}"

    - name: List BeeGFS nodes with NIC details
      ansible.builtin.command:
        cmd: "beegfs-ctl --listnodes --nodetype={{ item }} --nicdetails"
      with_items:
        - meta
        - storage
        - client
      when: inventory_hostname == first_client_node

    - name: Check BeeGFS network
      ansible.builtin.command:
        cmd: beegfs-net
      when: inventory_hostname == first_client_node

    - name: Check BeeGFS servers
      ansible.builtin.command:
        cmd: beegfs-check-servers
      when: inventory_hostname == first_client_node

    - name: Check BeeGFS disk space
      ansible.builtin.command:
        cmd: beegfs-df
      when: inventory_hostname == first_client_node

