---
- name: Disable firewall and selinux 
  hosts: all
  any_errors_fatal: true
  gather_facts: false # needed for {{ ansible_architecture }}, do it later so we can wait for ssh

  tasks:
    - name: Include wait_ssh task
      include_tasks: wait_ssh.yaml

    - name: Gather facts
      setup:

    - name: Check SELinux status
      command: getenforce
      register: selinux_status
      changed_when: false
      tags:
        - selinux
        - lustre
        - config
        - precheck

    - name: Debug SELinux status
      debug:
        msg: "SELinux status: {{ selinux_status.stdout }}"
      tags:
        - selinux
        - lustre
        - config
        - precheck

    - name: Disable SELinux if it is Enforcing or Permissive
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
      when: selinux_status.stdout != "Disabled"
      register: disable_selinux

    - name: Set SELinux to disabled immediately
      command: setenforce 0
      when: selinux_status.stdout != "Disabled"
      register: setenforce_result

    - name: Ensure disable_selinux is defined
      set_fact:
        disable_selinux: "{{ disable_selinux | default({'changed': False}) }}"

    - name: Ensure setenforce_result is defined
      set_fact:
        setenforce_result: "{{ setenforce_result | default({'changed': False}) }}"

    - name: Check firewall status
      service_facts:
      tags:
        - config
        - firewall

    - name: Debug - Print firewall status
      debug:
        msg: "Firewall status: {{ ansible_facts.services.firewalld if 'firewalld' in ansible_facts.services else 'not found' }}"

    - name: Check if firewalld service exists
      ansible.builtin.command: systemctl status firewalld
      ignore_errors: yes
      register: firewalld_status

    - name: Stop and disable and mask firewall (without mask, it will return after two reboots)
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: no
        masked: yes
      when: firewalld_status.rc == 0
      tags:
        - config
        - firewall

    - name: Ensure firewall_status is defined
      set_fact:
        firewall_status: "{{ firewall_status | default({'changed': False}) }}"

    - name: Reboot if SELinux or firewall was changed
      reboot:
        msg: "Rebooting to apply SELinux and/or firewall changes"
        reboot_timeout: 300
      when: disable_selinux.changed or setenforce_result.changed or firewall_status.changed

    - name: Wait for ssh after changing selinux setting 
      include_tasks: wait_ssh.yaml
      when: selinux is defined 

    - name: Verify SELinux is disabled after reboot
      command: getenforce
      register: selinux_status_after_reboot
      changed_when: false
      tags:
        - selinux
        - lustre
        - config
        - precheck

    - name: Assert SELinux is disabled
      assert:
        that:
          - selinux_status_after_reboot.stdout == "Disabled"
        fail_msg: "Error: SELinux is not disabled. Current status is {{ selinux_status_after_reboot.stdout }}"
      tags:
        - selinux
        - lustre
        - config
        - precheck

    - name: Verify firewall status after reboot
      service_facts:
      tags:
        - config
        - firewall

    - name: Assert firewall is stopped
      assert:
        that:
          - (ansible_facts.services.firewalld.state | default('stopped')) == "stopped"
        fail_msg: "Error: Firewall is not stopped. Current status is {{ ansible_facts.services.firewalld.state | default('not found') }}"
      tags:
        - config
        - firewall

