# this inventory is an initial attempt at creating a fedora VM to work as a local dnf cache 
# https://gitlab.newmexicoconsortium.org/jbent/tassi/-/blob/main/doc/lustre_install/lustre_vm.pdf
# additionally, the node on which this is run might need to be set up correctly:
# https://gitlab.newmexicoconsortium.org/jbent/tassi/-/blob/main/doc/lustre_install/john_notes.txt
all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
    ansible_playbooks:
        install: './ansible/install_empty.yaml'
        config: './ansible/configure_empty.yaml'
        test: './ansible/test_empty.yaml'
    test_script: 
        path: './tests/test_pdsh.sh'
        args: 'dnflocal' 
    vm_dir: '/mnt/usrc-storage-nfs/jbent/images' 
    boot_vm_name: 'bootstrap_dnf'
    bootstrap_vm:
      cpus: 2
      boot_hdd_gbs: 12
      memory_mbs: 4096
      root_pwd: password
      location: '/mnt/usrc-storage-nfs/jbent/images/fedora/Fedora-Server-netinst-x86_64-40-1.14.iso'
      location: '/mnt/usrc-storage-nfs/jbent/images/fedora/fedora-coreos-40.20240709.3.1-qemu.x86_64.qcow2'
      os_variant: ' fedora-coreos-stable'
      auth_keys: '/home/jbent/.ssh/authorized_keys'
    network: 
      addr: '192.168.56'
    system:
      type: 'dnflocal'
  children:
    clients:
      vars:
        hds: [5]
      hosts:
        dnflocal:
          ip: 83
