---
- name: "Gather Current Status of All Nodes"
  hosts: all
  gather_facts: yes
  vars_files:
    - ./lustre_vars.yaml
  vars:
    packages:
      - name: "lustre"
        module_command: "lsmod | grep -q lustre"
        version_command: "lctl --version | awk '{print $2}'"
      - name: "zfs"
        module_command: "lsmod | grep -q zfs"
        version_command: "zfs --version | head -1"
    dbg_versions: {}
    dbg_lsmod: {}
    expected_versions:
      lustre: "{{ lustre_version }}"
      zfs: "zfs-2.1.11-1"

  tasks:
    - block:
        - name: Display all gathered facts
          debug:
            var: ansible_facts
          when: False

        - name: Gather lsmod status for each package
          shell: "{{ item.module_command }}"
          register: lsmod_result
          changed_when: false
          ignore_errors: yes
          failed_when: lsmod_result.rc not in [0, 1]
          loop: "{{ packages }}"
          loop_control:
            loop_var: item

        - name: Gather version for each package
          shell: "{{ item.version_command }}"
          register: version_result
          changed_when: false
          ignore_errors: yes
          loop: "{{ packages }}"
          loop_control:
            loop_var: item

        - name: Set versions from gathering
          set_fact:
            dbg_versions: "{{ dbg_versions | combine({ item.item.name: (item.stdout if item.stdout | length > 0 else 'n/a') }) }}"
          loop: "{{ version_result.results }}"
          no_log: true

        - name: Assert Lustre version
          assert:
            that:
              - "'lustre' in dbg_versions"
              - "dbg_versions.lustre == expected_versions.lustre"
            fail_msg: "Lustre version is not as expected (expected {{ expected_versions.lustre }}, found {{ dbg_versions.lustre }})"
            success_msg: "Lustre version is as expected ({{ expected_versions.lustre }})"

        - name: Assert ZFS version
          assert:
            that:
              - "'zfs' in dbg_versions"
              - "dbg_versions.zfs == expected_versions.zfs"
            fail_msg: "ZFS version is not as expected (expected {{ expected_versions.zfs }}, found {{ dbg_versions.zfs }})"
            success_msg: "ZFS version is as expected ({{ expected_versions.zfs }})"

        - name: Set lsmod status from gathering
          set_fact:
            dbg_lsmod: >-
              {{
                dbg_lsmod | combine({ item.item.name: (item.rc == 0) })
              }} 
          loop: "{{ lsmod_result.results }}"
          no_log: true

        - name: Display Mounts 
          debug:
            msg: |
              Mounts: {{ ansible_facts['mounts'] }}
          when: False

        # ANSIBLE_STDOUT_CALLBACK=debug needs to be set for this to look good
        - name: Display Pertinent Facts 
          debug:
            msg: |
              Node: {{ inventory_hostname }} {{ ansible_hostname }}
              OS: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}
              Architecture: {{ ansible_facts['architecture'] }}
              Date/Time: {{ ansible_facts['date_time']['iso8601'] }}
              HDD Size: {{ ansible_facts['devices']['dm-0']['size'] }}
              Mem Total: {{ ansible_facts['memtotal_mb'] }}
              Proc Count: {{ ansible_facts['processor_count'] }}
              Python: {{ ansible_facts['python_version'] }}
              Uptime: {{ ansible_facts['uptime_seconds'] }}
              ZFS Module Loaded : {{ dbg_lsmod.zfs }}
              ZFS Version : {{ dbg_versions.zfs }}
              Lustre Module Loaded : {{ dbg_lsmod.lustre }}
              Lustre Version : {{ dbg_versions.lustre }}

      tags: health

