all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
    mgs_node: '192.168.56.10@tcp:192.168.56.20@tcp'
    network: 
      addr: '192.168.56'
      name: 'hostonly-net'
    lustre_options: 'options lnet ip2nets="tcp0(enp8s0) 192.168.56.[10,20,30,40,50]"'
    lustre_repo: /usr/local/src/lustre-release
    lustre_version: 2.15.4
    zfs_version: zfs-2.1.11 
  children:
    small_lustre:
      children:
        small_lustre_clients:
          vars:
            configure_args: '--disable-server --enable-client'
          hosts:
            client:
              ip: 50
              target_mount: '/mnt/lustre'
              hds: []
        small_lustre_servers:
          vars:
            configure_args: '--with-zfs --disable-ldiskfs --enable-server'
          children:
            mds:
              hosts:
                mds00:
                  target_type: mdt
                  ip: 10
                  failnode: 20
                  index: 0
                  mgt_mount: '/mnt/lustre/mgt'
                  mgt_target: 'lustre-mgs' 
                  target: 'lustre-mds00/mdt0'
                  target_mount: '/mnt/lustre/mds00.mdt0'
                  hds: [5, 5]
                mds01:
                  target_type: mdt
                  ip: 20
                  failnode: 10
                  index: 1
                  target: 'lustre-mds01/mdt0'
                  target_mount: '/mnt/lustre/mds01.mdt0'
                  hds: [5]
            oss:
              hosts:
                oss00:
                  target_type: ost
                  ip: 30
                  failnode: 40
                  index: 0
                  target: 'lustre-oss00/ost0'
                  target_mount: '/mnt/lustre/oss00.ost0'
                  hds: [10]
                oss01:
                  target_type: ost
                  ip: 40
                  failnode: 30
                  index: 1
                  target: 'lustre-oss01/ost0'
                  target_mount: '/mnt/lustre/oss01.ost0'
                  hds: [10]
