all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
  children:
    small_lustre:
      children:
        small_lustre_clients:
          hosts:
            client:
          vars:
            configure_args: '--disable-server --enable-client'
        small_lustre_servers:
          children:
            mds:
              hosts:
                mds00:
                  target_type: mdt
                  failnode: 20
                  index: 0
                  target: 'lustre-mds00/mdt0'
                mds01:
                  target_type: mdt
                  failnode: 10
                  index: 1
                  target: 'lustre-mds01/mdt0'
            oss:
              hosts:
                oss00:
                  target_type: ost
                  failnode: 40
                  index: 0
                  target: 'lustre-oss00/ost0'
                oss01:
                  target_type: ost
                  failnode: 30
                  index: 1
                  target: 'lustre-oss01/ost0'
          vars:
            configure_args: '--with-zfs --disable-ldiskfs --enable-server'

