---
- name: Global Setup
  hosts: all
  gather_facts: no
  vars:
    ior_config_option: '--with-lustre'

- name: Install ZFS
  import_playbook: install_zfs.yaml

- name: Install Lustre
  import_playbook: install_lustre.yaml

- name: Install Tools
  import_playbook: install_tools.yaml

#- name: Configure Lustre
#  import_playbook: configure_lustre.yaml

#- name: Test Lustre
#  import_playbook: test_striping.yaml
