---
- name: Global Setup of DNF local server
  hosts: all
  gather_facts: no
  vars:
    ior_config_option: '' # no config options for empty install

- import_playbook: disable_firewall_selinux.yaml

- hosts: all
  tasks:
    - name: Ensure required packages are installed
      dnf:
        name:
          - squid 
          - lsof
          - net-tools
        state: present

