---
- name: Install OpenMPI on {{ target_hosts }}
  hosts: all 
  any_errors_fatal: true
  gather_facts: false 
  vars:
    zfs_repo: /usr/local/src/zfs

  tasks:
    - name: Wait for SSH to become ready
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        timeout: 300
      delegate_to: localhost
      become: false
      when: "'clients' in group_names"

    - name: Install OpenMPI and development packages
      dnf:
        name:
          - openmpi
          - openmpi-devel
        state: present
      when: "'clients' in group_names"

    - name: Ensure Environment Modules are initialized in /etc/bashrc
      lineinfile:
        path: /etc/bashrc
        line: 'source /etc/profile.d/modules.sh'
        create: yes
      when: "'clients' in group_names"

    - name: Load OpenMPI environment module in a new script
      lineinfile:
        path: /etc/profile.d/openmpi.sh
        line: 'module load mpi/openmpi-x86_64'
        create: yes
      when: "'clients' in group_names"

    - name: Reboot the system to apply changes
      reboot:
      when: "'clients' in group_names"

    - name: Wait for SSH to become available after reboot
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        timeout: 120
        delay: 10
      when: "'clients' in group_names"

