---
- name: Install and Build Lustre
  hosts: all
  gather_facts: true # needed for {{ ansible_architecture }}
  any_errors_fatal: true
  vars_files:
    - ./lustre_vars.yaml

  tasks:
    - name: Update dnf cache
      dnf:
        update_cache: yes
      tags: 
        - dependencies
        - lustre

    - name: Disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      tags: 
        - firewalld
        - lustre
        - config

    - name: Check status of firewalld
      systemd:
        name: firewalld
        state: started
      register: firewalld_status
      ignore_errors: yes
      tags: 
        - firewalld
        - lustre
        - config


    - name: Print firewalld status
      debug:
        msg: "Firewalld is currently {{ 'enabled' if firewalld_status.status.ActiveState == 'active' else 'disabled' }}"
      tags: 
        - firewalld
        - lustre
        - config


    - name: Disable SELinux
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*$'
        replace: 'SELINUX=disabled'
      register: selinux_config
      tags: 
        - selinux
        - lustre
        - config


    - name: Check SELinux status
      command: sestatus
      register: sestatus_output
      tags: 
        - selinux
        - lustre
        - config

    - name: Print SELinux status
      debug:
        msg: "SELinux is currently {{ 'enabled' if 'enforcing' in sestatus_output.stdout else 'disabled' }}"
      tags: 
        - selinux
        - lustre
        - config

    - name: Install Lustre dependencies - Development Tools
      dnf:
        name: '@Development Tools'
        state: latest
      tags: 
        - dependencies
        - lustre

    - name: Install Lustre dependencies - General packages
      dnf:
        name:
          - epel-release
          - xmlto
          - asciidoc
          - elfutils-libelf-devel
          - zlib-devel
          - kernel-devel
          - libyaml-devel
          - binutils-devel
          - newt-devel
          - python3-devel
          - hmaccalc
          - perl-ExtUtils-Embed
          - bison
          - elfutils-devel
          - audit-libs-devel
          - python3-docutils
          - sg3_utils
          - expect
          - attr
          - lsof
          - quilt
          - libselinux-devel
          - libmount-devel
          - libnl3-cli
          - libnl3-devel
          - resource-agents
        state: latest
        enablerepo: 
          - powertools
          - ha
      tags: 
        - dependencies
        - lustre

    - name: Clone and checkout Lustre 
      git:
        repo: 'git://git.whamcloud.com/fs/lustre-release.git'
        dest: "{{ lustre_repo }}"
        version: "tags/{{ lustre_version }}"
        clone: yes
        update: yes
      tags: 
        - build
        - lustre

    - name: Configure Lustre
      shell: |
        cd "{{ lustre_repo }}"
        sh autogen.sh
        ./configure {{configure_args}} --with-linux=/usr/src/kernels/$(uname -r)
        make -j$(nproc)
      args:
        executable: /bin/bash
      tags: 
        - build
        - lustre

    - name: Build Lustre
      shell: |
        cd "{{ lustre_repo }}"
        make -j$(nproc) 
      args:
        executable: /bin/bash
      tags: 
        - build
        - lustre

    - name: Run llmountcleanup.sh
      command: "{{ lustre_repo }}/lustre/tests/llmountcleanup.sh"
      when: "group_names | join(' ') | regex_search('lustre_servers')" # only run on servers
      tags: 
        - cleanup
        - lustre

    - name: Remove /sbin/mount.lustre if it exists
    # sometimes make install fails due to errors with this file
      file:
        path: /sbin/mount.lustre
        state: absent
      register: result
      ignore_errors: true
      failed_when: >
        result.failed and ('No such file or directory' not in result.msg)
      tags: 
        - cleanup
        - lustre

    - name: Install Lustre
      shell: |
        cd "{{ lustre_repo }}"
        make -j$(nproc) install
      args:
        executable: /bin/bash
      tags: 
        - install
        - lustre

    - name: Build Lustre RPMS
      shell: |
        cd "{{ lustre_repo }}"
        make -j$(nproc) rpms
      args:
        executable: /bin/bash
      tags: 
        - install
        - lustre
        - rpms 

    - name: Ensure RPM destination directory exists
      file:
        path: "{{ lustre_rpms }}"
        state: directory
        mode: '0755'
      tags: 
        - install
        - lustre
        - rpms

    - name: Move RPM files
      shell: "mv *.{{ ansible_architecture }}.rpm {{ lustre_rpms }}"
      args:
        executable: /bin/bash
        chdir: "{{ lustre_repo }}"
      tags: 
        - install
        - lustre
        - rpms
