- name: Install and Build Lustre
  hosts: all

  tasks:
    - name: Update dnf cache
      dnf:
        update_cache: yes

    - name: Install Lustre dependencies - Development Tools
      dnf:
        name: '@Development Tools'
        state: latest

    - name: Install Lustre dependencies - General packages
      dnf:
        name:
          - epel-release
          - xmlto
          - asciidoc
          - elfutils-libelf-devel
          - zlib-devel
          - kernel-devel
          - libyaml-devel
          - binutils-devel
          - newt-devel
          - python3-devel
          - hmaccalc
          - perl-ExtUtils-Embed
          - bison
          - elfutils-devel
          - audit-libs-devel
          - python3-docutils
          - sg3_utils
          - expect
          - attr
          - lsof
          - quilt
          - libselinux-devel
          - libmount-devel
          - libnl3-cli
          - libnl3-devel
        state: latest
        enablerepo: powertools

    - name: Clone and checkout Lustre 2.15
      git:
        repo: 'git://git.whamcloud.com/fs/lustre-release.git'
        dest: '/lustre-release'
        version: 'tags/2.15.4'
        clone: yes
        update: yes

    - name: Build Lustre
      shell: |
        cd /lustre-release
        sh autogen.sh
        ./configure --with-zfs --disable-ldiskfs --with-linux=/usr/src/kernels/$(uname -r)
        make -j$(nproc)
      args:
        executable: /bin/bash


    - name: Install Lustre
      shell: |
        cd /lustre-release
        make -j$(nproc) install
      args:
        executable: /bin/bash

