---
- name: Global Setup
  hosts: all
  gather_facts: no
  vars:
    ior_config_option: '' # no config options for empty install 

  tasks:
    - name: Include disable firewall and selinux
      include_tasks: disable_firewall_selinux.yaml

- import_playbook: install_tools.yaml
