---
- name: Global Install of BeeGFS Cluster
  hosts: all
  gather_facts: no
  vars:
    ior_config_option: '' # no config options for beegfs install 

- import_playbook: install_beegfs.yaml

- import_playbook: install_tools.yaml

- import_playbook: disable_firewall_selinux.yaml
