---
- name: Global Setup
  hosts: all
  gather_facts: no
  vars:
    ior_config_option: '' # ior doesn't seem to have a flag for beegfs

- name: Install BeeGFS
  import_playbook: install_beegfs.yaml

- name: Install Tools
  import_playbook: install_tools.yaml

#- name: Configure Lustre
#  import_playbook: configure_lustre.yaml

#- name: Test Lustre
#  import_playbook: test_striping.yaml
