---
- name: Global Setup of DNF local server
  hosts: all
  gather_facts: no
  vars:
    ior_config_option: '' # no config options for empty install

- import_playbook: disable_firewall_selinux.yaml

- hosts: all
  tasks:
    - name: Ensure Apache and required packages are installed
      dnf:
        name:
          - httpd
          - createrepo
          - dnf-plugins-core
          - python3-dnf-plugin-local
        state: present

