---
- name: Install Lustre and Essentials
  hosts: all
  gather_facts: no
  vars:
    ior_config_option: '--with-lustre'
  
- import_playbook: install_zfs.yaml

- import_playbook: install_lustre.yaml

- import_playbook: install_tools.yaml

- import_playbook: disable_firewall_selinux.yaml
