---
- name: Install Lustre and Essentials
  hosts: all
  gather_facts: no
  vars:
    ior_config_option: '' # no config options for empty install 
  
- name: Install ZFS
  import_playbook: install_zfs.yaml

- name: Install Lustre
  import_playbook: install_lustre.yaml

- name: Install Tools
  vars:
    ior_config_option: '--with-lustre'
  import_playbook: install_tools.yaml

- name: Include disable firewall and selinux
  import_playbook: disable_firewall_selinux.yaml

#- name: Configure Lustre
#  import_playbook: configure_lustre.yaml

#- name: Test Lustre
#  import_playbook: test_striping.yaml
