---
- name: Global Setup of Empty Cluster
  hosts: all
  gather_facts: no
  vars:
    ior_config_option: '' # no config options for empty install 

- name: Install Tools
  import_playbook: install_tools.yaml

- name: Include disable firewall and selinux
  import_playbook: disable_firewall_selinux.yaml

