- name: Define kernel RPMs list
  set_fact:
    kernel_rpms:
      - kernel-devel-{{ ansible_kernel }}.rpm
      - kernel-headers-{{ ansible_kernel }}.rpm
      - kernel-abi-stablelists-{{ ansible_kernel | regex_replace('(\.[^.]+)$', '') }}.noarch.rpm
  tags:
    - dependencies

- name: Copy kernel RPMs from host NFS mount to VM /tmp
  copy:
    src: /mnt/usrc-storage-nfs/jbent/images/rpms/{{ item }}
    dest: /tmp/{{ item }}
  loop: "{{ kernel_rpms }}"
  tags:
    - dependencies

- name: Install kernel RPMs from local files in /tmp
  command:
    cmd: dnf install -y /tmp/{{ item }}
  loop: "{{ kernel_rpms }}"
  tags:
    - dependencies
    - kernel

