---
- name: Install BeeGFS
  hosts: all
  become: yes
  gather_facts: false # needed for {{ ansible_architecture }}, do it later so we can wait for ssh
  vars:
    selinux: disabled  # or permissive, enforcing
  tasks:
    - name: Include wait_ssh task
      include_tasks: wait_ssh.yaml

    - name: Gather facts
      setup:

    - name: Remove existing BeeGFS repo files if present
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/yum.repos.d/beegfs.repo
        - /etc/yum.repos.d/beegfs-*.repo

    - name: Install EPEL repository
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Install yum-utils
      ansible.builtin.dnf:
        name: yum-utils
        state: present

    - name: Install rsync on all nodes
      ansible.builtin.package:
        name: rsync
        state: present
      become: yes

    - name: Set BeeGFS repository URL
      ansible.builtin.set_fact:
        repo_url: 'https://www.beegfs.io/release/beegfs_{{ system.version }}/dists/rhel8/'

    - name: Create BeeGFS repository file with correct URL
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/beegfs.repo
        content: |
          [beegfs]
          name=BeeGFS
          baseurl={{ repo_url }}
          gpgcheck=0
          enabled=1

    - name: Ensure BeeGFS repository is configured correctly
      ansible.builtin.command: ls -l /etc/yum.repos.d/
      register: repo_dir_contents

    - name: Print BeeGFS repo directory contents
      ansible.builtin.debug:
        var: repo_dir_contents.stdout_lines

    - name: Verify BeeGFS repository file contents
      ansible.builtin.command: cat /etc/yum.repos.d/beegfs.repo
      register: beegfs_repo_contents

    - name: Print BeeGFS repository file contents
      ansible.builtin.debug:
        var: beegfs_repo_contents.stdout_lines

    - name: Clean the DNF cache
      ansible.builtin.command:
        cmd: dnf clean all
      become: yes

    - name: Regenerate the DNF metadata cache
      ansible.builtin.command:
        cmd: dnf makecache
      become: yes

    - name: Install BeeGFS management packages
      ansible.builtin.dnf:
        name:
          - beegfs-mgmtd
          - beegfs-helperd
          - beegfs-utils
        state: present
      #when: inventory_hostname == 'meta00'
      when: "'servers' in group_names"

    - name: Install BeeGFS metadata packages
      ansible.builtin.dnf:
        name:
          - beegfs-meta
        state: present
      #when: inventory_hostname == 'meta01'
      when: "'servers' in group_names"

    - name: Install BeeGFS storage packages
      ansible.builtin.dnf:
        name:
          - beegfs-storage
        state: present
      when: "'servers' in group_names"
      #when: "'data' in group_names"

    - name: Install BeeGFS client packages
      ansible.builtin.dnf:
        name:
          - beegfs-client
          - beegfs-helperd
        state: present
      when: "'clients' in group_names"

    - name: Install BeeGFS common packages
      ansible.builtin.dnf:
        name:
          - beegfs-common
          - beegfs-utils
        state: present

    - name: Install kernel development packages on clients
      ansible.builtin.dnf:
        name:
          #- kernel-devel
          #- kernel-headers
          - "kernel-devel-{{ ansible_kernel }}"
          - "kernel-headers-{{ ansible_kernel }}"
          - gcc
          - make
        state: present
      when: "'clients' in group_names"

    - name: Rebuild BeeGFS modules on clients
      ansible.builtin.command:
        cmd: /etc/init.d/beegfs-client rebuild
      when: "'clients' in group_names"
