---
- name: Global Setup
  hosts: all
  gather_facts: no

- name: Install ZFS
  import_playbook: install_zfs.yaml

- name: Install Lustre
  import_playbook: install_lustre.yaml

- name: Connectivity Test
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping Test
      ping:
  tags: 
    - health

- name: Assert Version 
  import_playbook: get_status.yaml 

- name: Test Single Node Lustre 
  import_playbook: test_lustre.yaml 
