---
- name: Global Setup of DNF Mirror Server
  hosts: all
  gather_facts: no

- import_playbook: disable_firewall_selinux.yaml

- hosts: all
  tasks:
    - name: Ensure Apache and required packages for DNF mirror are installed
      dnf:
        name:
          - httpd
          - createrepo
          - dnf-plugins-core
          - rsync
          - yum-utils
          - nfs-utils
        state: present

