---
- name: Install ZFS on {{ target_hosts }}
  hosts: all 
  vars:
    zfs_repo: /usr/local/src/zfs


  tasks:
    - name: Install EPEL repository and ZFS dependencies phase 1
      dnf:
        name:
          # from https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html
          - epel-release
          - gcc
          - make
          - autoconf
          - automake
          - libtool
          - rpm-build
          - kernel-rpm-macros
          - libtirpc-devel
          - libblkid-devel
          - libuuid-devel
          - libudev-devel
          - openssl-devel
          - zlib-devel
          - libaio-devel
          - libattr-devel
          - elfutils-libelf-devel
          - kernel-devel-{{ ansible_kernel }}
          - kernel-abi-stablelists-{{ ansible_kernel | regex_replace('(\.[^.]+)$', '') }}
          - python3
          - python3-devel
          - python3-setuptools
          - python3-cffi
          - libffi-devel
          - ncompress
        enablerepo:
          - epel
        state: present
        skip_broken: true
      tags: dependencies

    - name: Install EPEL repository and ZFS dependencies phase 2
      dnf:
        name:
          - python3-packaging
          - dkms
        enablerepo:
          - epel
          - powertools
        state: present
        skip_broken: true
      tags: dependencies

    - name: Install Git
      dnf:
        name: git
        state: present
      tags: dependencies

    - name: Clone ZFS repository
      git:
        repo: https://github.com/openzfs/zfs.git
        dest: "{{ zfs_repo }}"
        version: tags/zfs-2.1.11
        clone: yes
        update: yes
      tags: build

    - name: Build and install ZFS
      shell: |
        cd "{{ zfs_repo }}"
        ./autogen.sh
        ./configure --with-spec=redhat
        make pkg-utils pkg-kmod
      args:
        executable: /bin/bash
      tags: build

    - name: Install ZFS RPMs
      shell: dnf localinstall *.{{ ansible_architecture }}.rpm
      args:
        executable: /bin/bash
        chdir: "{{ zfs_repo }}"
      when: False
      tags: install

    - name: Find RPM files in zfs installation
      find:
        paths: "{{ zfs_repo }}"
        patterns: "*.{{ ansible_architecture }}.rpm"
      register: rpm_files
      tags: install

    - name: Install ZFS RPMs
      dnf:
        name: "{{ rpm_files.files | map(attribute='path') | list }}"
        state: present
        disable_gpg_check: yes
      tags: install

    - name: Load ZFS kernel module
      modprobe:
        name: zfs
        state: present
      tags: install

