- name: Create test file
  command: dd if=/dev/zero of=/mnt/lustre/file.out bs=1MB count=200

- name: Wait for 10 seconds
  pause:
    seconds: 10

- name: Get striping info
  shell: df -h /mnt/lustre-ost* | grep -v Filesystem | awk '{print $3}' | tr '\n' ' '
  register: striping_info

- name: Display striping info
  debug:
    msg: "Host {{ ansible_hostname }} - Stripes with {{ striping_pattern }} pattern: {{ striping_info.stdout }}"

- name: Remove test file
  file:
    path: /mnt/lustre/file.out
    state: absent

- name: Wait for 10 seconds
  pause:
    seconds: 10

