---
- name: Test Lustre 
  hosts: all
  vars_files:
    - ./lustre_vars.yaml
  tasks:
    - name: Create test file
      command: dd if=/dev/zero of=/mnt/lustre/file.out bs=1MB count=200
      when: "'small_lustre_clients' in group_names"

    - name: Wait for 10 seconds
      pause:
        seconds: 10

    - name: Get striping info
      shell: df -h /mnt/lustre/*ost0* | grep -v Filesystem | awk '{print $3}' | tr '\n' ' '
      register: striping_info
      when: "'oss' in group_names"

    - name: Display striping info
      debug:
        #msg: "Host {{ ansible_hostname }} - Stripes with {{ striping_pattern }} pattern: {{ striping_info.stdout }}"
        msg: "Host {{ ansible_hostname }} - Stripes with default pattern: {{ striping_info.stdout }}"
      when: "'oss' in group_names"

    - name: Remove test file
      file:
        path: /mnt/lustre/file.out
        state: absent
      when: "'small_lustre_clients' in group_names"

    - name: Wait for 10 seconds
      pause:
        seconds: 10

