---
- name: Test BeeGFS setup
  hosts: clients
  become: yes
  gather_facts: no
  tasks:
    - name: Get the list of client nodes
      set_fact:
        client_nodes: "{{ groups['clients'] }}"

    - name: Set the first client node
      set_fact:
        first_client_node: "{{ client_nodes | first }}"

    - name: Calculate number of processes
      set_fact:
        num_processes: "{{ 1 * client_nodes | length }}"

    - name: Generate host list for mpirun
      set_fact:
        host_list: "{{ client_nodes | join(',') }}"

    - name: Run MPI IOR test on first client
      ansible.builtin.command:
        cmd: "mpirun --allow-run-as-root -np {{ num_processes }} -host {{ host_list }} ior -o /mnt/beegfs/ior.np2.t1m.b16m.s16 -t 1m -b 16m -s 16"
      when: inventory_hostname == first_client_node

