---
- name: Test Lustre Setup
  hosts: all
  vars_files:
    - ./lustre_vars.yaml
  tasks:
    - name: Check if llmount.sh exists
      stat:
        path: "{{ lustre_repo }}/lustre/tests/llmount.sh"
      register: llmount
      when: "'servers' in group_names"
        
    - name: Fail if llmount.sh does not exist
      fail:
        msg: "Warning: {{ lustre_repo }}/lustre/tests/llmount.sh does not exist."
      when: 
        - "'servers' in group_names"
        - not llmount.stat.exists
     
    - name: Check if running as root
      fail: 
        msg: "Warning: This script must be run as root."
      when: ansible_user_id != 'root'

    - name: Change striping behavior to N-N
      command: "{{ lustre_repo }}/lustre/utils/lfs setstripe -c 1 /mnt/lustre"
      when: "'clients' in group_names"

    - name: Test striping function (N-N)
      include_tasks: test_striping.yaml
      vars:
        striping_pattern: "N-N"

    - name: Change striping behavior to N-1
      command: "{{ lustre_repo }}/lustre/utils/lfs setstripe -c -1 /mnt/lustre"
      when: "'clients' in group_names"
  
    - name: Test striping function (N-1)
      include_tasks: test_striping.yaml
      vars:
        striping_pattern: "N-1"

