---
- name: Test Lustre 
  hosts: all
  vars_files:
    - ./lustre_vars.yaml
  tasks:
    - name: Check if llmount.sh exists
      stat:
        path: "{{ lustre_repo }}/lustre/tests/llmount.sh"
      register: llmount

    - name: Fail if llmount.sh does not exist
      fail:
        msg: "Warning: {{ lustre_repo }}/lustre/tests/llmount.sh does not exist."
      when: not llmount.stat.exists

    - name: Check if running as root
      fail:
        msg: "Warning: This script must be run as root."
      when: ansible_user_id != 'root'

    - name: Run llmountcleanup.sh
      command: "{{ lustre_repo }}/lustre/tests/llmountcleanup.sh"
      when: "group_names | join(' ') | regex_search('lustre_servers')" # only run on servers
  
    - name: Run llmount.sh with FSTYPE=zfs
      command: "/usr/local/src/lustre-release/lustre/tests/llmount.sh"
      environment:
        FSTYPE: zfs
      when: "group_names | join(' ') | regex_search('lustre_servers')" # only run on servers

    - name: Test striping function (Default Pattern)
      include_tasks: test_striping.yaml
      vars:
        striping_pattern: "default"
      when: "group_names | join(' ') | regex_search('lustre_servers')" # only run on servers

    - name: Change striping behavior
      command: "{{ lustre_repo }}/lustre/utils/lfs setstripe -c -1 /mnt/lustre"
      when: "group_names | join(' ') | regex_search('lustre_servers')" # only run on servers

    - name: Test striping function (Modified Pattern)
      include_tasks: test_striping.yaml
      vars:
        striping_pattern: "modified"
      when: "group_names | join(' ') | regex_search('lustre_servers')" # only run on servers

    - name: Run llmountcleanup.sh
      command: "{{ lustre_repo }}/lustre/tests/llmountcleanup.sh"
      when: "group_names | join(' ') | regex_search('lustre_servers')" # only run on servers
