#---
#- name: Test Lustre Striping
#  hosts: all
#  vars_files:
#    - ./lustre_vars.yaml
#  tasks:
- name: Create test file(s)
  command: dd if=/dev/zero of=/mnt/lustre/file.{{ ansible_hostname }} bs=1MB count=200
  when: "'clients' in group_names"

- name: Wait for 10 seconds
  pause:
    seconds: 10

- name: Get striping info
  shell: df -h /mnt/lustre/*ost0* | grep -v Filesystem | awk '{print $3}' | tr '\n' ' '
  register: striping_info
  when: "'oss' in group_names"

- name: Show striping info
  debug:
    msg: "{{ striping_info.stdout }}"
  when: "'oss' in group_names"

- name: Remove test file(s)
  file:
    path: /mnt/lustre/file.{{ ansible_hostname }}
    state: absent
  when: "'clients' in group_names"

- name: Wait for 10 seconds
  pause:
    seconds: 10

