# wait_ssh.yaml
---
- name: Loop to check SSH and possibly reboot VM
  include_tasks: retry_ssh.yaml

- name: Ping each host to verify connectivity
  ping:
  register: ping_result

- name: Fail if ping does not succeed
  fail:
    msg: "Ping test failed for {{ inventory_hostname }}. Check connectivity and try again."
  when: ping_result.ping != "pong"
